# Generate Jobs Report Data for Chartbook

Brian Dew

@bd_econ

In [1]:
import sys
sys.path.append('../src')

import uschartbook.config

from uschartbook.config import *
from uschartbook.utils import *

### API Request

In [2]:
# Series stored as a dictionary
series = {'LNS14000003': 'White', 
          'LNS14000006': 'Black',
          'LNS14000009': 'Hispanic',
          'LNS14032183': 'Asian',
          'LNS14000000': 'Total',
          'LNS13327709': 'U6',
          'LNS13000000': 'Level',
          'LNU05026639': 'WantJob',
          'LNU03008636': 'LT',
          'LNU03008516': 'MT',
          'LNU00000000': 'POP',
          'LNS12300060': 'PA_EPOP',
          'LNS13023621': 'Job Loser',
          'LNS13023653': 'Temporary Layoff',
          'LNS13026638': 'Permanent Separation',
          'LNS13023705': 'Job Leaver', 
          'LNS13023557': 'Re-entrant',
          'LNS13023569': 'New entrant',
          'LNS13008276': 'Median',
          'LNS13008275': 'Mean',
          'LNS17200000': 'NILF',
          'LNS17100000': 'UNEMP',
          'LNS11000000': 'LF',
          'LNS12032194': 'PTECON',
          'LNS12005977': 'PTNONECON'}

# Start year and end year
dates = (1988, 2025)
df = bls_api(series, dates, bls_key)
df.to_csv(data_dir / 'jobs_report_main.csv', index_label='date')
print(dtxt(df.index[-1])['mon1'])

Post Request Status: REQUEST_SUCCEEDED
December 2025

In [14]:
# data = b'''
# Series ID,Jan 1988,Feb 1988,Mar 1988,Apr 1988,May 1988,Jun 1988,Jul 1988,Aug 1988,Sep 1988,Oct 1988,Nov 1988,Dec 1988,Jan 1989,Feb 1989,Mar 1989,Apr 1989,May 1989,Jun 1989,Jul 1989,Aug 1989,Sep 1989,Oct 1989,Nov 1989,Dec 1989,Jan 1990,Feb 1990,Mar 1990,Apr 1990,May 1990,Jun 1990,Jul 1990,Aug 1990,Sep 1990,Oct 1990,Nov 1990,Dec 1990,Jan 1991,Feb 1991,Mar 1991,Apr 1991,May 1991,Jun 1991,Jul 1991,Aug 1991,Sep 1991,Oct 1991,Nov 1991,Dec 1991,Jan 1992,Feb 1992,Mar 1992,Apr 1992,May 1992,Jun 1992,Jul 1992,Aug 1992,Sep 1992,Oct 1992,Nov 1992,Dec 1992,Jan 1993,Feb 1993,Mar 1993,Apr 1993,May 1993,Jun 1993,Jul 1993,Aug 1993,Sep 1993,Oct 1993,Nov 1993,Dec 1993,Jan 1994,Feb 1994,Mar 1994,Apr 1994,May 1994,Jun 1994,Jul 1994,Aug 1994,Sep 1994,Oct 1994,Nov 1994,Dec 1994,Jan 1995,Feb 1995,Mar 1995,Apr 1995,May 1995,Jun 1995,Jul 1995,Aug 1995,Sep 1995,Oct 1995,Nov 1995,Dec 1995,Jan 1996,Feb 1996,Mar 1996,Apr 1996,May 1996,Jun 1996,Jul 1996,Aug 1996,Sep 1996,Oct 1996,Nov 1996,Dec 1996,Jan 1997,Feb 1997,Mar 1997,Apr 1997,May 1997,Jun 1997,Jul 1997,Aug 1997,Sep 1997,Oct 1997,Nov 1997,Dec 1997,Jan 1998,Feb 1998,Mar 1998,Apr 1998,May 1998,Jun 1998,Jul 1998,Aug 1998,Sep 1998,Oct 1998,Nov 1998,Dec 1998,Jan 1999,Feb 1999,Mar 1999,Apr 1999,May 1999,Jun 1999,Jul 1999,Aug 1999,Sep 1999,Oct 1999,Nov 1999,Dec 1999,Jan 2000,Feb 2000,Mar 2000,Apr 2000,May 2000,Jun 2000,Jul 2000,Aug 2000,Sep 2000,Oct 2000,Nov 2000,Dec 2000,Jan 2001,Feb 2001,Mar 2001,Apr 2001,May 2001,Jun 2001,Jul 2001,Aug 2001,Sep 2001,Oct 2001,Nov 2001,Dec 2001,Jan 2002,Feb 2002,Mar 2002,Apr 2002,May 2002,Jun 2002,Jul 2002,Aug 2002,Sep 2002,Oct 2002,Nov 2002,Dec 2002,Jan 2003,Feb 2003,Mar 2003,Apr 2003,May 2003,Jun 2003,Jul 2003,Aug 2003,Sep 2003,Oct 2003,Nov 2003,Dec 2003,Jan 2004,Feb 2004,Mar 2004,Apr 2004,May 2004,Jun 2004,Jul 2004,Aug 2004,Sep 2004,Oct 2004,Nov 2004,Dec 2004,Jan 2005,Feb 2005,Mar 2005,Apr 2005,May 2005,Jun 2005,Jul 2005,Aug 2005,Sep 2005,Oct 2005,Nov 2005,Dec 2005,Jan 2006,Feb 2006,Mar 2006,Apr 2006,May 2006,Jun 2006,Jul 2006,Aug 2006,Sep 2006,Oct 2006,Nov 2006,Dec 2006,Jan 2007,Feb 2007,Mar 2007,Apr 2007,May 2007,Jun 2007,Jul 2007,Aug 2007,Sep 2007,Oct 2007,Nov 2007,Dec 2007,Jan 2008,Feb 2008,Mar 2008,Apr 2008,May 2008,Jun 2008,Jul 2008,Aug 2008,Sep 2008,Oct 2008,Nov 2008,Dec 2008,Jan 2009,Feb 2009,Mar 2009,Apr 2009,May 2009,Jun 2009,Jul 2009,Aug 2009,Sep 2009,Oct 2009,Nov 2009,Dec 2009,Jan 2010,Feb 2010,Mar 2010,Apr 2010,May 2010,Jun 2010,Jul 2010,Aug 2010,Sep 2010,Oct 2010,Nov 2010,Dec 2010,Jan 2011,Feb 2011,Mar 2011,Apr 2011,May 2011,Jun 2011,Jul 2011,Aug 2011,Sep 2011,Oct 2011,Nov 2011,Dec 2011,Jan 2012,Feb 2012,Mar 2012,Apr 2012,May 2012,Jun 2012,Jul 2012,Aug 2012,Sep 2012,Oct 2012,Nov 2012,Dec 2012,Jan 2013,Feb 2013,Mar 2013,Apr 2013,May 2013,Jun 2013,Jul 2013,Aug 2013,Sep 2013,Oct 2013,Nov 2013,Dec 2013,Jan 2014,Feb 2014,Mar 2014,Apr 2014,May 2014,Jun 2014,Jul 2014,Aug 2014,Sep 2014,Oct 2014,Nov 2014,Dec 2014,Jan 2015,Feb 2015,Mar 2015,Apr 2015,May 2015,Jun 2015,Jul 2015,Aug 2015,Sep 2015,Oct 2015,Nov 2015,Dec 2015,Jan 2016,Feb 2016,Mar 2016,Apr 2016,May 2016,Jun 2016,Jul 2016,Aug 2016,Sep 2016,Oct 2016,Nov 2016,Dec 2016,Jan 2017,Feb 2017,Mar 2017,Apr 2017,May 2017,Jun 2017,Jul 2017,Aug 2017,Sep 2017,Oct 2017,Nov 2017,Dec 2017,Jan 2018,Feb 2018,Mar 2018,Apr 2018,May 2018,Jun 2018,Jul 2018,Aug 2018,Sep 2018,Oct 2018,Nov 2018,Dec 2018,Jan 2019,Feb 2019,Mar 2019,Apr 2019,May 2019,Jun 2019,Jul 2019,Aug 2019,Sep 2019,Oct 2019,Nov 2019,Dec 2019,Jan 2020,Feb 2020,Mar 2020,Apr 2020,May 2020,Jun 2020,Jul 2020,Aug 2020,Sep 2020,Oct 2020,Nov 2020,Dec 2020,Jan 2021,Feb 2021,Mar 2021,Apr 2021,May 2021,Jun 2021,Jul 2021,Aug 2021,Sep 2021,Oct 2021,Nov 2021,Dec 2021,Jan 2022,Feb 2022,Mar 2022,Apr 2022,May 2022,Jun 2022,Jul 2022,Aug 2022,Sep 2022,Oct 2022,Nov 2022,Dec 2022,Jan 2023,Feb 2023,Mar 2023,Apr 2023,May 2023,Jun 2023,Jul 2023,Aug 2023,Sep 2023,Oct 2023,Nov 2023,Dec 2023,Jan 2024,Feb 2024,Mar 2024,Apr 2024,May 2024,Jun 2024,Jul 2024,Aug 2024,Sep 2024,Oct 2024,Nov 2024,Dec 2024,Jan 2025,Feb 2025,Mar 2025,Apr 2025,May 2025,Jun 2025,Jul 2025,Aug 2025,Sep 2025,Oct 2025,Nov 2025,Dec 2025
# LNS12300061,89.4,89.5,89.4,89.8,89.5,89.3,89.6,89.4,89.5,89.5,89.5,89.4,89.9,89.8,89.9,89.7,89.8,90.0,89.9,90.0,89.7,89.8,89.9,90.0,89.9,90.1,89.8,89.4,89.3,89.3,89.0,88.9,88.7,88.6,88.5,88.1,88.2,88.0,87.7,87.9,87.4,87.5,87.5,87.4,87.5,87.2,87.1,86.9,86.9,86.6,86.8,86.9,86.8,86.9,86.9,86.9,86.8,86.7,86.6,86.7,86.8,86.7,86.5,86.8,87.0,87.1,87.1,87.2,87.1,87.1,87.5,87.4,87.1,86.8,87.0,87.1,87.3,87.0,87.0,87.0,87.4,87.5,87.9,88.0,87.9,88.1,87.9,87.7,87.6,87.6,87.5,87.4,87.6,87.6,87.2,87.2,87.5,87.7,87.5,87.5,87.6,87.8,88.1,88.4,88.1,88.3,88.2,88.3,88.2,88.2,88.2,88.1,88.1,88.4,88.6,88.7,88.6,88.6,88.7,88.6,88.8,88.9,88.8,88.9,88.8,88.7,88.7,88.8,88.8,88.8,89.1,88.9,89.7,89.2,89.2,89.1,88.9,88.8,88.8,88.7,88.6,88.7,89.0,89.0,89.5,89.4,89.3,89.2,89.0,89.1,88.9,88.9,88.6,88.6,88.8,88.9,88.9,88.8,88.5,88.3,88.3,88.1,87.9,87.6,87.6,87.4,87.0,87.1,86.8,87.1,87.0,86.8,86.9,86.5,86.5,86.8,86.8,86.6,85.9,86.0,85.6,85.9,85.8,85.9,85.7,85.8,85.8,85.7,85.9,85.9,86.0,86.4,86.4,86.2,86.0,86.2,86.3,86.5,86.7,86.5,86.4,86.3,86.5,86.2,86.5,86.7,86.8,87.0,87.1,87.0,87.0,87.4,87.0,87.0,86.8,86.7,87.2,87.1,87.4,87.2,87.2,87.2,87.1,87.1,87.4,87.4,87.5,87.7,88.0,87.9,88.0,87.9,87.7,87.5,87.3,87.2,87.1,86.9,87.2,87.2,87.4,87.4,87.1,86.7,86.5,86.3,86.2,85.8,85.4,85.2,84.7,83.7,83.1,82.5,82.0,81.8,81.5,81.5,81.3,81.2,80.8,80.8,80.7,80.4,80.7,80.6,80.8,81.3,81.1,81.1,81.1,81.2,81.2,81.1,80.7,80.8,81.2,81.4,81.4,81.2,81.6,81.3,81.1,81.4,81.3,81.1,81.9,82.1,82.5,82.4,82.5,82.5,82.5,82.6,82.4,82.4,82.7,82.9,82.5,82.8,82.6,82.8,82.8,82.8,83.0,82.9,82.9,82.6,82.6,82.4,83.0,83.0,83.2,83.0,83.5,83.2,83.3,83.8,83.8,83.9,84.1,84.0,83.9,84.2,84.3,84.3,84.5,84.4,84.3,84.5,84.4,84.6,84.6,84.4,84.4,84.5,84.9,84.9,85.2,84.8,84.9,85.1,84.9,84.9,84.9,85.0,85.0,85.0,85.3,85.2,85.2,85.5,85.3,85.4,85.3,85.0,85.6,85.6,85.5,86.0,86.0,86.4,86.2,86.3,86.4,86.1,86.2,86.0,85.9,86.1,86.2,86.0,86.5,86.5,86.7,86.4,86.3,86.2,86.2,86.2,86.4,86.5,86.7,86.5,86.7,86.4,85.7,75.9,78.0,79.5,79.8,81.5,81.5,82.2,82.0,82.4,82.6,82.6,82.6,82.8,83.0,83.1,83.8,84.0,84.2,84.7,85.0,85.2,85.1,85.8,85.8,85.9,86.0,85.8,85.8,85.9,86.1,85.9,85.8,86.3,85.9,86.2,86.3,86.3,86.4,86.4,86.5,86.4,86.4,86.0,86.3,86.2,86.2,86.3,86.3,86.1,86.0,86.5,86.6,86.3,86.4,86.3,86.1,86.1,86.4,86.1,86.0,86.4,86.1,86.4,85.9,86.5,86.3,-(9),86.1, 
# LNS12300062,68.7,68.7,69.2,69.1,69.1,69.1,69.2,69.4,69.4,69.7,70.1,70.2,70.5,70.4,70.2,70.3,70.1,70.1,70.0,70.2,70.7,70.5,70.8,70.7,70.9,70.8,70.8,70.7,70.8,70.6,70.6,70.5,70.5,70.4,70.2,70.1,69.9,70.1,70.0,70.3,70.1,70.2,70.1,70.0,70.1,70.0,70.0,69.9,70.1,70.0,70.0,70.2,70.3,70.3,70.2,70.2,70.1,70.0,70.1,69.9,69.9,69.9,70.3,69.9,70.2,70.4,70.4,70.6,70.5,70.5,70.7,71.0,71.0,71.3,71.1,71.2,71.3,70.9,71.4,71.7,72.1,71.9,72.0,71.8,71.8,72.2,72.1,72.2,72.1,71.7,72.2,72.1,72.3,72.3,72.6,72.4,72.4,72.4,72.6,72.6,72.5,72.7,72.9,73.0,73.0,73.1,73.0,73.0,73.2,72.9,73.3,73.5,73.3,73.6,73.9,74.1,73.9,73.8,73.6,73.6,73.4,73.4,73.5,73.5,73.4,73.6,73.8,73.9,74.0,73.7,73.7,74.0,74.3,74.1,73.8,73.8,74.1,74.2,73.8,74.1,74.3,74.5,74.5,74.3,74.4,74.5,74.5,74.9,74.4,74.2,73.9,73.6,73.9,73.9,74.1,74.1,74.2,74.2,74.3,73.7,73.7,73.4,73.4,73.2,73.1,72.7,72.6,72.6,72.5,72.7,72.5,72.5,72.2,72.1,71.9,72.1,72.2,72.1,71.9,72.2,72.4,72.1,72.4,72.4,72.2,72.3,71.9,72.0,71.6,71.6,71.7,71.4,71.6,71.7,71.8,71.8,71.9,71.9,71.9,71.8,71.9,71.9,72.0,71.8,72.0,71.9,71.8,72.0,72.1,71.7,71.9,72.1,72.1,71.9,71.9,72.1,72.2,72.4,72.3,72.1,72.3,72.5,72.7,72.6,72.5,72.9,72.7,72.7,72.8,72.6,72.7,72.2,72.5,72.5,72.4,72.6,72.5,72.4,72.5,72.4,72.7,72.6,72.6,72.7,72.6,72.6,72.4,72.1,72.3,71.9,71.7,71.6,71.1,71.0,70.6,70.7,70.4,70.4,70.4,70.0,69.5,69.4,69.8,69.2,69.8,69.7,69.5,69.6,69.3,69.5,69.1,69.0,69.1,69.0,69.1,69.4,69.3,69.0,69.3,69.1,68.9,68.8,69.0,68.9,68.7,68.9,68.8,68.9,68.9,68.9,69.2,69.1,69.2,69.0,69.1,69.2,69.5,69.6,69.4,69.4,68.9,69.0,69.0,69.1,69.3,69.2,69.4,69.6,69.6,69.0,69.3,69.5,69.8,70.1,69.8,69.9,69.8,70.2,69.8,70.1,69.8,70.1,70.3,70.3,70.2,70.3,70.0,70.2,70.4,70.5,70.1,70.2,70.2,70.3,70.7,70.6,70.7,70.8,70.9,70.9,71.0,71.0,71.4,71.1,71.4,71.5,71.4,71.4,71.3,71.7,72.0,72.0,72.0,72.1,72.4,72.1,72.5,72.1,72.5,72.2,72.1,72.4,72.4,72.3,72.5,72.8,73.1,72.8,73.0,73.4,73.1,73.3,73.3,73.4,73.1,73.2,73.3,73.5,73.1,73.9,74.2,74.3,74.2,74.5,74.6,74.6,73.4,63.4,64.9,67.6,68.0,69.1,68.9,70.1,70.3,70.5,70.4,70.7,71.1,71.1,71.3,71.3,71.9,71.9,72.0,72.3,73.0,73.4,73.4,73.2,74.2,73.9,74.1,73.9,74.1,74.7,74.4,74.0,73.9,74.2,74.7,74.8,75.0,75.1,75.1,75.3,75.3,75.3,75.3,75.3,75.2,74.8,75.0,75.2,75.1,75.5,75.7,75.1,75.3,75.6,75.5,74.9,74.8,75.0,75.1,75.1,74.9,75.0,74.9,75.2,75.0,75.0,75.1,-(9),75.1, 
# LNS12005054,39.2,39.3,39.4,39.8,39.4,39.4,39.3,39.3,39.2,39.5,39.2,39.3,39.4,39.4,39.4,39.2,39.4,39.4,39.5,39.6,39.6,39.6,39.6,39.5,39.5,39.5,39.4,39.4,39.2,39.5,39.4,39.4,39.4,39.3,39.4,39.3,39.2,39.2,39.1,38.9,39.1,39.1,39.1,39.2,39.1,39.2,39.1,39.0,39.2,39.3,39.3,39.2,39.2,39.2,39.2,39.1,39.0,39.2,39.2,39.2,39.2,39.3,39.3,39.4,39.4,39.3,39.3,39.4,39.4,39.4,39.4,39.5,39.0,38.4,39.2,39.6,39.3,39.3,39.3,39.2,39.2,39.2,38.9,39.3,39.3,39.1,39.2,39.2,39.1,39.3,39.3,39.3,39.2,39.3,39.4,39.3,37.8,39.4,39.3,39.3,39.3,39.3,39.2,39.3,39.4,39.5,39.5,39.3,39.1,39.3,39.4,39.3,39.5,39.5,39.4,39.4,39.5,39.4,39.4,39.5,39.6,39.5,39.4,39.5,39.5,39.4,39.6,39.5,39.1,39.5,39.5,39.8,39.4,39.6,39.5,39.6,39.5,39.6,39.5,39.6,39.1,39.6,39.7,39.7,39.7,39.9,39.7,39.8,39.7,39.5,39.7,39.6,39.7,39.6,39.6,39.5,39.5,39.4,39.4,39.4,39.4,39.4,39.4,39.3,38.6,39.2,39.2,39.2,39.3,39.1,39.1,39.0,39.1,39.1,39.0,39.1,39.1,39.0,39.1,38.7,39.0,39.0,39.0,39.1,39.0,39.0,39.0,39.0,39.0,39.1,39.0,39.0,39.1,39.1,39.1,39.0,39.0,38.9,39.0,38.9,38.8,39.0,39.0,39.2,39.0,39.1,39.0,38.9,39.0,39.2,39.1,39.1,39.2,39.1,39.2,39.1,39.2,39.2,39.1,39.5,39.2,39.2,39.3,39.3,39.3,39.2,39.0,39.3,39.1,38.8,39.2,39.1,39.2,39.1,39.1,39.1,39.0,39.1,39.5,39.1,39.1,39.0,39.0,38.8,38.9,39.0,38.8,38.8,38.7,38.7,38.6,38.4,38.3,38.3,38.2,38.1,38.0,37.9,38.0,38.0,38.5,37.8,38.0,38.0,38.2,37.4,38.1,38.4,38.2,38.2,38.2,38.1,38.2,38.2,38.1,38.2,37.7,38.2,38.3,38.3,38.3,38.3,38.3,38.2,38.3,38.3,38.3,38.4,38.3,38.4,38.3,38.4,38.3,38.4,38.4,38.5,38.4,38.5,38.7,38.5,38.5,38.6,38.6,38.6,38.6,38.6,38.4,38.6,38.6,38.9,39.0,38.3,38.6,38.0,38.6,38.7,38.7,38.6,38.4,38.7,38.8,38.7,38.7,38.8,38.8,38.7,38.8,38.7,38.7,38.7,38.8,38.8,38.8,38.8,38.6,38.8,38.8,38.7,38.9,38.9,38.7,38.8,38.7,38.7,38.8,38.6,38.6,38.7,38.6,38.9,38.6,38.8,38.8,38.9,38.8,38.7,38.5,38.8,38.8,38.9,38.7,38.9,38.7,38.9,38.9,38.9,39.0,39.0,38.8,38.9,39.2,38.9,39.0,38.7,38.8,38.9,38.9,38.9,39.0,39.0,39.0,39.1,39.3,38.9,38.9,38.8,38.4,37.6,37.8,38.1,38.3,38.5,38.9,38.5,38.5,38.7,38.9,38.6,38.8,38.8,38.7,38.7,38.7,38.7,38.7,38.7,38.7,38.9,38.5,39.0,38.9,38.8,38.7,38.7,38.6,38.7,38.6,38.7,38.5,38.5,38.6,38.7,38.5,38.5,38.6,38.5,38.5,38.5,38.4,38.4,38.4,38.4,38.2,38.4,38.2,38.3,38.2,38.3,38.2,38.3,38.3,38.2,38.4,38.2,38.4,38.2,38.3,38.4,38.2,38.2,38.1,38.2,38.3,-(9),38.3, 
# LNU02033699, , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , ,34.8,34.9,35.2,35.2,35.5,36.1,36.4,36.2,35.6,35.1,35.2,35.1,34.9,34.7,35.2,35.0,35.4,36.0,36.2,36.2,35.0,35.0,34.8,34.8,34.6,34.6,34.8,35.0,35.3,35.7,35.9,35.8,35.1,34.9,34.6,34.6,34.4,34.2,34.7,34.7,35.1,35.2,35.6,35.7,34.9,34.8,34.4,34.7,34.4,34.4,34.5,34.7,34.9,35.3,35.7,36.0,35.3,35.1,34.6,35.1,34.8,34.7,34.8,35.1,35.0,35.8,35.8,35.8,35.3,34.8,34.9,35.1,34.9,35.0,35.4,34.8,35.2,35.9,36.1,36.2,35.6,35.3,35.2,35.3,34.9,34.7,35.3,35.1,35.5,35.6,35.8,35.6,35.3,35.1,35.2,35.1,35.2,34.9,35.0,35.0,35.1,35.5,35.7,35.7,35.3,35.0,34.5,34.4,34.2,33.9,33.9,34.0,34.3,34.6,34.9,34.7,33.2,34.1,33.9,33.7,33.8,33.3,34.0,34.3,34.5,34.6,34.9,34.8,34.4,34.3,33.8,33.9,33.5,33.7,33.8,34.0,34.5,34.5,34.6,34.6,34.4,34.3,34.0,34.5,33.9,34.2,34.0,34.1,34.3,34.4,34.7,35.0,34.6,34.6,34.6,34.5,33.9,34.1,34.1,34.1,34.6,34.7,34.9,35.3,34.7,34.6,34.5,34.4,34.1,33.3,34.3,34.3,34.8,34.7,34.9,35.0,34.6,34.5,34.3,34.6,34.4,34.5,34.7,34.4,34.9,34.9,35.3,35.1,33.9,34.7,34.6,35.0,34.6,34.4,34.9,34.8,34.5,35.0,35.3,35.6,35.0,34.7,34.5,34.8,34.5,34.7,34.8,34.9,35.2,35.3,35.6,35.5,34.9,35.0,34.8,34.9,34.6,35.2,35.0,35.2,35.4,35.5,35.8,35.4,35.0,35.0,35.2,35.1,34.9,34.5,34.8,34.9,35.4,35.6,35.9,35.7,35.4,35.3,35.3,35.3,34.6,34.7,33.8(C),33.6,33.4,34.4,34.0,34.7,34.1,34.5,34.4,34.6,34.4,33.8,34.4,34.4,34.8,34.9,35.4,35.2,35.1,34.9,34.8,35.1,34.4,34.4,34.8,34.6,35.2,35.5,35.2,35.0,35.0,34.8,34.5,34.4,34.3,34.7,34.8,34.9,34.9,35.5,35.3,35.1,34.7,34.8,34.3,34.4,33.9,34.4,34.3,34.7,34.6,35.2,35.1,35.1,34.8,34.4,34.4,34.4,34.4,34.0,34.2,34.4,34.5,35.0,34.7,34.8,34.7,-(9),34.3, 
# LNU02033232,22.0,22.0,22.6,22.4,22.3,21.8,22.1,22.1,21.9,22.5,21.7,22.1,22.2,21.9,22.5,22.1,22.3,22.1,22.2,22.2,22.2,22.5,22.5,22.2,22.6,22.5,22.7,22.6,22.6,22.2,22.6,22.3,22.5,22.4,22.6,22.3,22.2,22.8,22.8,22.3,22.6,21.9,22.3,22.3,22.5,22.8,22.3,22.3,22.2,22.2,22.2,22.4,22.6,22.3,22.2,22.4,21.8,22.4,22.2,22.1,22.0,22.1,22.2,22.7,22.5,22.2,22.5,22.3,22.7,22.4,22.3,22.7,22.6,22.0,22.6,22.8,22.6,22.6,22.6,22.8,22.5,22.8,22.3,22.8,22.6,22.8,23.1,22.8,23.0,23.0,22.8,23.3,23.2,23.0,22.6,22.6,22.2,22.8,22.8,22.9,22.7,22.7,22.7,22.8,22.8,23.0,22.7,22.8,22.2,23.2,22.8,23.2,23.0,22.7,22.9,23.2,23.1,23.3,23.1,23.0,22.8,23.0,23.1,23.2,23.0,22.5,23.1,22.4,22.3,23.2,23.1,23.4,22.4,23.2,23.1,23.1,23.6,23.1,22.9,22.9,23.3,23.4,23.2,23.1,23.2,23.0,23.3,24.1,23.6,23.0,22.9,23.2,23.0,23.1,23.9,23.1,23.0,22.9,23.6,23.7,23.2,23.2,23.2,22.9,23.2,23.7,23.4,23.2,22.8,22.6,23.0,23.2,23.0,23.2,22.7,23.2,23.5,23.6,22.9,22.6,22.5,22.9,23.0,22.9,23.3,22.5,22.8,23.1,23.3,23.4,23.0,23.2,22.6,22.6,23.2,23.0,23.0,23.0,22.6,23.0,23.1,23.3,22.9,23.0,22.5,22.8,23.0,23.3,23.0,23.2,23.0,22.7,23.3,22.9,23.0,22.9,22.9,22.8,23.0,22.8,23.2,23.0,22.8,23.1,23.3,23.5,23.1,23.4,22.8,22.9,23.0,23.1,23.3,23.1,22.9,23.0,23.2,23.2,23.5,23.2,22.9,22.5,22.9,23.1,23.3,23.2,22.8,23.1,23.0,23.2,22.8,22.7,22.3,22.8,23.1,22.8,23.1,22.6,22.5,22.8,22.3,22.8,22.4,22.4,22.2,21.8,22.3,22.8,22.6,22.5,22.4,22.6,22.8,22.4,22.5,22.4,22.1,22.3,22.4,22.6,22.7,22.6,22.4,22.4,22.7,23.1,22.7,22.6,22.4,22.8,22.6,22.8,22.8,22.4,22.6,22.7,23.1,22.8,22.8,22.9,22.3,22.7,23.0,23.1,22.9,22.9,23.1,23.1,23.0,23.1,23.2,22.7,22.7,22.3,22.8,23.2,23.3,23.2,22.7,22.9,23.2,23.1,23.0,23.3,22.9,22.9,23.0,23.0,22.9,23.0,23.0,23.0,22.7,23.3,22.8,23.2,22.7,22.7,23.3,23.3,23.7,23.0,23.1,23.0,23.2,23.3,23.5,23.0,22.5,23.1,23.2,23.4,23.6,23.3,22.8,22.4,23.1,23.4,22.9,23.2,22.8,23.0,23.0,23.9,23.5,23.0,23.1,22.9,23.3,23.3,23.3,23.5,23.1,22.6,23.1,23.0,23.3,23.1,23.0,23.1,23.3,23.8,23.8,23.2,22.7,22.9,22.8,21.0,21.5,21.9,21.9,22.3,22.0,22.4,22.6,22.2,22.1,21.7,22.1,22.6,22.3,22.4,22.4,22.2,22.7,22.8,23.2,23.2,22.6,22.9,23.1,22.9,23.0,22.2,22.4,22.7,23.5,23.2,22.9,22.9,22.7,23.4,23.6,23.4,23.2,22.7,22.9,23.0,23.0,23.6,22.8,23.1,22.8,22.9,23.2,22.9,23.4,22.6,22.7,22.3,22.6,22.8,23.2,22.4,22.8,22.1,22.9,23.1,23.5,22.5,22.3,22.1,23.2,-(9),22.6, 
# LNU01000000,119742,119942,119957,120264,120775,123028,123888,123396,121842,122432,122639,122120,122095,121906,122223,122576,123196,125569,126238,125444,123828,124416,124664,123998,124358,124487,124838,124837,125682,127407,128019,127105,125785,126067,125858,125635,124623,125061,125435,125698,125863,128143,128458,127197,126426,126636,126466,126150,126114,126425,126843,126911,127777,130197,130844,129676,128196,127998,128245,128035,127186,127651,127829,127616,128949,131060,131574,130673,128975,129685,129662,129537,129393,129764,129718,129682,130602,132115,132783,132361,131155,131879,131869,131418,130698,131028,131423,131657,131739,133447,134440,133383,132341,132863,132622,132008,131396,131995,132692,132513,133558,135083,136272,135011,134230,135015,134973,134583,134317,134535,135524,135181,135963,137557,138331,137460,136375,136665,136912,136742,135951,136286,136967,136379,137240,138798,139336,138379,137903,138255,138288,138297,137943,138202,138418,138240,138919,140666,141119,140090,139217,139761,139895,139941,141228(1),141775,142123,142138,142144,143874,143797,143171,142149,142685,142797,143110,142828,143100,143664,143026,143023,144553,145097,143826,143601,144060,143987,144042,143228,144266,144334,144158,144527,145940,146189,145565,145167,145320,144854,144807,145301(1),145693,145801,145925,146067,148117,147822,146967,146166,146787,146969,146501,146068(1),146154,146525,146260,146659,148478,149217,148166,147186,147978,148246,147877,147125(1),147649,147745,148274,148878,150327,151122,150469,149838,150304,150239,149874,149090(1),149686,150027,150209,150696,152557,153208,152465,151635,152397,152590,152571,151924(1),151879,152236,151829,152350,154252,154871,153493,153400,153516,154035,153705,152828(1),152503,153135,153208,154003,155582,156300,155387,154509,155012,154624,154349,153445(1),153804,153728,153834,154336,155921,156255,154897,153617,153635,153539,152693,152957(1),153194,153660,153911,153866,154767,155270,154678,153854,153652,153698,153156,152536(1),152635,153022,152898,153449,154538,154812,154344,154022,154088,153683,153373,153485(1),154114,154316,153905,154998,156385,156526,155255,155075,155779,154953,154904,154794(1),154727,154512,154739,155734,157089,157196,155971,155536,154918,155046,154408,154381(1),155027,155627,154845,155841,156997,157573,156434,155903,156616,156297,155521,156050(1),156213,156318,156554,157719,158283,158527,157390,156607,157313,157340,157245,157347(1),158279,158854,158488,158800,160135,160705,159800,159636,159783,159451,158968,158676(1),159482,159912,159817,159979,161337,161911,160863,161049,160465,160466,159880,160037(1),161494,161548,161280,161765,163277,163734,161909,161958,162723,162665,162510,162104(1),162793,162823,162097,162655,164120,164941,164019,163943,164576,164386,164007,163497(1),164235,162537,155830,157975,160883,161374,160966,160073,161053,160468,160017,159234(1),160008,160397,160379,160607,162167,162817,161788,161392,161863,162099,161696,162825(1),163725,164274,163449,164157,165012,165321,164971,164463,164753,164272,164224,165070(1),166178,166783,166221,166702,167910,168354,168049,167718,167774,167977,166661,166428(1),167285,167960,167484,167576,169007,169723,168763,168569,168569,168164,167746,169814(1),170116,170653,170650,170216,171343,171646,171035,171217,-(9),171467, 
# LNS12026619, , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , ,7116,6956,7174,7367,7151,7130,7218,7325,7608,7345,7345,7391,7521,7675,7605,7773,7767,7887,7825,7849,7751,7666,7472,7546,7458,7804,7891,7563,7660,7745,7682,7844,7901,8070,8309,8043,7870,7820,7830,7946,8003,8305,8093,7949,7931,7874,7961,7909,7954,7828,7931,8018,7945,7824,7665,7856,7993,8002,8117,7998,8113,7982,7940,7735,7751,7615,7645,7701,7641,7827,7908,7800,7895,7687,7656,7885,7652,7448,7588,7515,7550,7445,7415,7556,7366,7517,7555,7439,7496,7469,7498,7389,7319,7036,7112,7105,7186,7326,7361,7443,7252,7374,7244,7210,7267,7157,7243,7416,7351,7492,7285,7279,7389,7378,7306,7549,7091,7323,7283,7044,7284,7144,7291,7334,7329,7425,7522,7688,7575,7797,7601,7644,7375,7610,7535,7502,7425,7755,7597,7535,7605,7572,7508,7521,7597,7400,7531,7389,7696,7355,7448,7552,7697,7624,7768,7867,7716,7711,7748,7832,7693,7614,7619,7550,7550,7636,7692,7538,7602,7536,7454,7576,7567,7782,7767,8071,7686,7635,7430,7415,7466,7573,7668,7700,7141,7117,7333,7086,7102,7094,7121,6887,6948,7034,7011,7028,7059,6956,6657,6811,6711,6730,6708,6899,6816,6741,6735,6823,6880,6946,6850,6940,6995,6917,6946,6977,7022,6966,6954,6903,6980,6804,6916,6921,6865,6888,7060,7003,6899,7281,7068,7002,6966,7108,7115,7077,6995,6877,6776,6851,6817,7012,6996,7158,7195,7105,7016,7144,7130,7610,7318,7220,7412,7068,7100,7017,7027,7197,7224,7234,7302,7430,7356,7757,7401,7327,7432,7420,7460,7224,7286,7529,7867,7884,7932,7620,7574,7855,8009,7620,7570,7538,7377,7219,7365,7219,7470,7707,7893,7961,7633,7650,7426,7583,7909,7814,7684,7915,7815,7940,7867,7670,7899,7794,7900,8132,8390,8340,8356,8165,8154,7947,8220,8035,7221,5380,5538,6226,6629,6781,6489,6721,6584,6406,6645,6667,6873,6909,7287,7114,7075,7031,7040,7017,7067,7354,7460,7423,7355,7562,7354,7568,7639,7759,7746,7518,7659,8020,8008,7899,7983,7708,7763,8025,8161,8061,8152,8367,8328,8566,8268,8264,8474,8385,8402,8346,8475,8537,8653,8308,8577,8478,8764,8860,8936,8866,8583,8865,8342,8785,8802,-(9),9301, 
# LNU02000000,112139,112460,112867,113905,114222,116209,117066,116737,115474,116250,116314,115978,114786,115023,115844,116347,117039,118719,119502,119092,117498,118194,118168,117698,116944,117192,117986,118218,119148,120523,120882,120096,118782,119175,118463,118110,115837,115941,116440,117472,117428,119151,119666,118758,118156,118404,117972,117395,115928,116024,116929,117776,118388,119831,120744,120070,118880,119185,119159,118990,117027,117646,118350,118781,120142,121587,122352,122018,120673,121389,121568,121578,119901,120503,120844,121604,122946,123864,124503,124493,123775,124724,124896,124729,122597,123343,123943,124278,124554,125720,126548,125926,125173,125979,125599,125136,123126,124137,124992,125388,126391,127706,128579,128143,127529,128439,128157,127903,126384,126887,128125,128629,129565,130463,131350,130865,129972,130671,130999,130785,128882,129482,130150,130735,131476,132265,132769,132206,131864,132424,132577,132732,131339,131639,132299,132552,133411,134395,134800,134264,133555,134390,134515,134696,134912(1),135490,136054,136927,136685,137915,137769,137308,136790,137532,137461,137846,136181,136577,137155,137022,137121,137737,138239,136809,136835,136885,136370,136269,134177,135443,135558,135903,136559,137181,137495,137295,137377,137551,136684,136599,135907(1),136433,136783,137424,137567,138468,138503,138137,137731,138619,138700,138556,136924(1),137384,137691,138423,138867,139861,140700,140226,139641,140447,140581,140278,138682(1),139100,139759,140939,141591,142456,143283,143142,142579,143340,142968,142918,141481(1),141994,142772,143405,144041,145216,145606,145379,145010,146125,146014,146081,144275(1),144479,145323,145297,145864,146958,147315,146406,146448,146743,147118,146334,144607(1),144550,145108,145921,145927,146649,146867,145909,145310,145543,144609,143350,140436(1),140105,139833,140586,140363,140826,141055,140074,139079,139088,139132,137953,136809(1),137203,137983,139302,139497,139882,140134,139919,139715,139749,139415,139159,137599(1),138093,138962,139661,140028,140129,140384,140335,140502,140987,141070,140681,139944(1),140684,141412,141995,142727,143202,143126,142558,143333,144039,143549,143060,141614(1),142228,142698,143724,144432,144841,145113,144509,144651,144144,144775,144423,143526(1),144134,145090,145767,146398,147104,147265,146647,146941,147936,147666,147190,146552(1),147118,147635,148587,149349,149645,149722,149228,148980,149716,149766,149703,149037(1),150060,150738,151075,151594,151990,152437,151804,151977,152335,152385,151798,150527(1),151594,152628,153262,153407,154086,154470,153576,154494,154223,154180,153602,152848(1),154403,154877,155348,156009,156465,157004,155539,156191,156952,157015,156481,154964(1),156167,156441,156710,157152,157828,158385,157816,158478,159067,158945,158504,156994(1),158017,155167,133326,137461,142811,144492,147224,147796,150433,150203,149613,148383(1),149522,150493,151160,151778,152283,153596,153232,154026,154966,155797,155732,155618(1),156942,158106,157991,158609,158678,159067,158714,159003,159144,158749,158872,158692(1),159713,160741,161075,161002,161559,161982,161427,161669,161676,162149,160754,159650(1),160315,161356,161590,161341,161774,162038,161348,162046,161938,161456,161294,162347(1),162544,163412,164069,163401,163883,163799,163288,163894,-(9),164066, 
# LNS12000000,114016,114227,114037,114650,114292,114927,115060,115282,115356,115638,116100,116104,116708,116776,117022,117097,117099,117418,117472,117655,117354,117581,117912,117830,119081,119059,119203,118852,119151,118983,118810,118802,118524,118536,118306,118241,117940,117755,117652,118109,117440,117639,117568,117484,117928,117800,117770,117466,117978,117753,118144,118426,118375,118419,118713,118826,118720,118628,118876,118997,119075,119275,119542,119474,120115,120290,120467,120856,120554,120823,121169,121464,121966,122086,121930,122290,122864,122634,122706,123342,123687,124112,124516,124721,124663,124928,124955,124945,124421,124522,124816,124852,125133,125388,125188,125088,125125,125639,125862,125994,126244,126602,126947,127172,127536,127890,127771,127860,128298,128298,128891,129143,129464,129412,129822,130010,130019,130179,130653,130679,130726,130807,130814,131209,131325,131244,131329,131390,131986,131999,132280,132602,133027,132856,132947,132955,133311,133378,133414,133591,133707,133993,134309,134523,136559(1),136598,136701,137270,136630,136940,136531,136662,136893,137088,137322,137614,137778,137612,137783,137299,137092,136873,137071,136241,136846,136392,136238,136047,135701,136438,136177,136126,136539,136415,136413,136705,137302,137008,136521,136426,137417(1),137482,137434,137633,137544,137790,137474,137549,137609,137984,138424,138411,138472(1),138542,138453,138680,138852,139174,139556,139573,139487,139732,140231,140125,140245(1),140385,140654,141254,141609,141714,142026,142434,142401,142548,142499,142752,143150(1),143457,143741,143761,144089,144353,144202,144625,144815,145314,145534,145970,146028(1),146057,146320,145586,145903,146063,145905,145682,146244,145946,146595,146273,146378(1),146156,146086,146132,145908,145737,145532,145203,145076,144802,144100,143369,142152(1),141640,140707,140656,140248,140009,139901,139492,138818,138432,138659,138013,138438(1),138581,138751,139297,139241,139141,139179,139438,139396,139119,139044,139301,139250(1),139394,139639,139586,139624,139384,139524,139942,140183,140368,140826,140902,141584(1),141858,142036,141899,142206,142391,142292,142291,143044,143431,143333,143330,143292(1),143362,143316,143635,143882,143999,144264,144326,144418,143537,144479,144778,145150(1),145134,145648,145667,145825,146247,146399,146530,146778,147427,147404,147615,148145(1),148045,148128,148511,148817,148816,148830,149181,148826,149246,149463,150128,150653(1),150939,151218,151074,151132,151223,151554,151779,151761,151793,151954,152157,152152(1),152480,153065,153255,153069,153318,153569,153503,154286,153609,153805,153904,154425(1),155197,155214,155312,155652,155762,156146,155504,156015,156391,156721,156817,156487(1),156863,156701,156625,156821,157232,157529,157829,158339,158545,158629,158845,158508(1),158714,155353,133185,137173,142342,143779,147245,147620,149931,149934,149975,149852(1),150189,150644,151081,151535,151734,152773,153250,153843,154475,155530,156099,157115(1),157598,158206,157891,158378,158094,158258,158735,158810,158684,158507,159259,160217(1),160395,160812,160974,160796,160979,161183,161475,161442,161211,161886,161124,161190(1),161013,161425,161495,161164,161155,161219,161425,161802,161456,161183,161661,163895(1),163307,163508,163969,163273,163366,163106,163394,163645,-(9),163741, 
# LNU00000001,87445,87522,87595,87656,87734,87844,87933,87975,88037,88111,88174,88258,88382,88452,88511,88573,88656,88736,88816,88865,88925,89002,89077,89153,89986,90039,90098,90181,90254,90332,90394,90467,90565,90658,90739,90812,90888,90940,90994,91063,91133,91213,91285,91372,91472,91579,91664,91739,91822,91882,91955,92035,92113,92196,92278,92377,92490,92606,92700,92783,92878,92956,93030,93108,93187,93274,93353,93442,93545,93642,93737,93826,93909,93982,94042,94119,94196,94294,94377,94469,94576,94671,94768,94851,94749,94818,94879,94952,95024,95110,95191,95287,95397,95492,95580,95661,95713,95786,95864,95955,96048,96140,96230,96335,96447,96556,96654,96742,97264,97320,97387,97474,97559,97649,97733,97838,97946,98050,98141,98225,98241,98331,98405,98503,98591,98691,98785,98892,99006,99121,99217,99309,99198,99279,99362,99465,99563,99668,99761,99863,99976,100088,100179,100264,101336,101424,101531,101667,101791,101909,102010,102134,102264,102392,102566,102546,102616,102753,102865,102991,103101,103214,103334,103459,103586,103710,103823,103928,104030,104114,104198,104293,104393,104501,104616,104738,104863,104985,105094,105195,105767,105895,106005,106123,106238,106362,106475,106604,106744,106879,107003,107123,107072,107177,107281,107392,107504,107625,107746,107881,108020,108153,108276,108392,108489,108598,108703,108812,108934,109062,109190,109332,109475,109616,109745,109863,109936,110048,110161,110280,110401,110530,110657,110792,110925,111059,111180,111288,111528,111627,111733,111849,111970,112093,112222,112354,112486,112619,112737,112852,112493,112596,112695,112803,112912,113029,113154,113281,113414,113546,113660,113769,113573,113666,113758,113857,113953,114060,114173,114288,114411,114530,114632,114728,114648,114735,114821,114910,115001,115102,115207,115317,115433,115542,115640,115731,115828,115907,115988,116067,116156,116250,116347,116453,116559,116664,116755,116832,116808,116896,116986,117081,117177,117277,117381,117492,117600,117710,117810,117902,118033,118117,118204,118296,118393,118490,118595,118700,118807,118916,119011,119103,119218,119306,119395,119488,119582,119680,119788,119893,120004,120112,120208,120301,120559,120647,120738,120831,120927,121032,121139,121250,121365,121474,121577,121671,121926,122017,122112,122213,122316,122427,122539,122656,122775,122889,122998,123099,122781,122862,122945,123032,123120,123215,123311,123413,123516,123617,123707,123786,124173,124250,124331,124418,124509,124604,124704,124816,124928,125041,125137,125227,124890,124965,125037,125114,125197,125285,125378,125481,125583,125687,125773,125852,125513,125575,125639,125707,125782,125860,125944,126036,126127,126218,126296,126367,126192,126224,126266,126316,126369,126434,126499,126570,126648,126719,126779,126832,128236,128296,128355,128411,128470,128547,128636,128722,128807,128897,128983,129050,129998,130072,130150,130234,130319,130408,130507,130608,130713,130816,130903,130985,130436,130520,130605,130694,130782,130875,130975,131077,131186,131287,131371,131455,133010,133089,133175,133260,133351,133449,133546,133651,133760,-(9),133957, 
# LNU00000002,96377,96447,96516,96576,96640,96718,96796,96855,96925,97003,97071,97144,97263,97325,97387,97451,97525,97593,97667,97733,97801,97869,97940,98012,98427,98478,98532,98597,98658,98726,98794,98875,98963,99052,99132,99205,99274,99331,99387,99453,99516,99587,99661,99744,99831,99918,99993,100060,100131,100185,100248,100320,100390,100467,100548,100641,100738,100836,100921,101001,101084,101152,101218,101290,101362,101445,101529,101621,101714,101802,101888,101969,102044,102107,102171,102244,102314,102399,102482,102575,102672,102758,102839,102913,103004,103068,103128,103197,103263,103342,103424,103514,103608,103700,103775,103847,103921,103986,104058,104146,104230,104319,104411,104512,104614,104717,104809,104894,105022,105068,105127,105200,105274,105351,105433,105527,105623,105718,105799,105873,105997,106070,106141,106228,106308,106394,106484,106587,106693,106798,106887,106960,107521,107593,107674,107771,107864,107964,108067,108175,108289,108395,108487,108569,110074,110152,110241,110351,110450,110557,110667,110782,110899,111013,110974,111191,111272,111357,111440,111534,111631,111735,111846,111961,112079,112193,112294,112387,112476,112549,112626,112713,112805,112906,113014,113127,113243,113355,113455,113546,114130,114219,114312,114417,114531,114653,114778,114903,115035,115160,115276,115386,115089,115180,115269,115365,115463,115570,115676,115796,115921,116039,116146,116247,116348,116443,116534,116629,116736,116849,116963,117089,117218,117343,117459,117562,117617,117715,117814,117919,118027,118141,118255,118376,118495,118616,118724,118820,119122,119207,119300,119403,119510,119620,119736,119856,119975,120096,120202,120304,120123,120213,120300,120396,120493,120598,120710,120825,120946,121066,121168,121266,121166,121247,121328,121415,121499,121594,121696,121799,121911,122020,122111,122197,122185,122263,122339,122419,122499,122589,122683,122783,122889,122988,123075,123158,122876,122944,123012,123079,123157,123239,123324,123418,123512,123605,123686,123753,125461,125539,125619,125703,125788,125878,125972,126073,126172,126273,126364,126447,126630,126710,126791,126878,126970,127062,127161,127260,127361,127465,127555,127642,127696,127779,127863,127951,128040,128133,128236,128336,128442,128545,128637,128726,129165,129252,129342,129434,129528,129631,129737,129846,129960,130067,130170,130265,130471,130561,130656,130756,130858,130969,131081,131198,131317,131432,131542,131643,131301,131384,131469,131556,131647,131742,131840,131943,132047,132149,132242,132323,132607,132684,132766,132853,132944,133038,133139,133250,133362,133474,133571,133662,133350,133427,133500,133579,133664,133753,133847,133951,134054,134158,134247,134329,133988,134053,134119,134189,134265,134344,134429,134523,134615,134707,134788,134862,134660,134694,134737,134787,134841,134905,134970,135041,135118,135189,135250,135304,134966,135028,135089,135148,135209,135287,135376,135462,135548,135638,135725,135795,135963,136040,136122,136209,136299,136393,136496,136605,136715,136826,136919,137006,137104,137191,137279,137372,137465,137564,137669,137779,137894,138002,138092,138183,139674,139758,139848,139937,140033,140136,140239,140350,140466,-(9),140676, 
# LNU01000001,65822,65907,65948,66229,66719,68101,68693,68326,66925,66925,66906,66627,66665,66752,66951,67163,67469,69213,69573,69068,67592,67928,67865,67639,68087,68140,68345,68423,68872,70103,70508,69932,68890,68990,68980,68857,68222,68448,68754,68753,68922,70335,70695,69898,69232,69027,68981,68753,68858,68975,69226,69286,69912,71330,71616,71009,70077,69824,69814,69638,69295,69617,69831,69670,70329,71658,72035,71518,70235,70410,70190,70064,69959,69998,70000,70026,70498,71549,72058,71748,70721,71168,71013,71060,70597,70691,70961,71054,71188,72394,72743,72133,71288,71324,71015,70936,70612,71011,71444,71450,72125,73165,73801,72888,72028,72436,72119,71959,72117,72214,72731,72755,73191,74312,74674,74149,73068,73345,73426,73153,72815,72930,73285,73336,73853,74945,75467,74540,73954,74165,74162,74055,73636,73718,73785,73837,74376,75472,75940,75190,74393,74623,74545,74631,75330,75717,75719,75781,75976,77260,77369,77151,76074,76316,76303,76359,76195,76224,76417,76509,76490,77618,78108,77296,76924,77054,76863,76929,76519,76846,77009,77026,77485,78419,78710,78169,77710,77641,77264,77197,77306,77658,77533,77796,77870,79162,79290,78640,78216,78392,78579,78413,78320,78014,78283,78147,78381,79762,80344,79832,78844,79282,79455,79093,78574,78950,79242,79448,79827,80985,81413,81079,80130,80306,80296,80140,79814,80148,80624,80669,80995,82062,82288,82027,81377,81652,81689,81715,81340,81344,81600,81665,81916,83050,83383,82541,82047,82177,82402,82171,81656,81515,81849,81864,82443,83432,84113,83296,82654,82772,82415,82226,81725,81959,81839,81878,82408,83141,83375,82704,81769,81823,81612,81243,81238,81488,81949,82014,82028,82669,83071,82685,81845,81675,81651,81504,81103,81360,81491,81354,81956,82757,82871,82612,82011,82081,82080,82019,81298,81609,81830,81629,82409,83369,83554,82669,82341,82715,82310,82190,82249,82180,82133,82201,82924,83837,83965,83110,82759,82261,82397,81985,81804,81954,82586,82104,82723,83850,84284,83567,83006,83075,82835,82800,82851,83040,83229,83358,84020,84461,84831,83996,83390,83572,83258,83439,83360,84052,84384,84323,84524,85790,86130,85416,84996,84991,84628,84463,84234,84589,84718,84851,85007,85970,86212,85633,85516,85236,84943,84831,85125,85806,85924,85965,86309,86988,87102,86212,85815,86081,85974,85857,85829,86056,86286,86027,86532,87415,88025,87155,86729,86824,86864,86500,86331,86597,85914,82820,83963,85429,85685,85600,85068,85464,84934,84644,84537,84754,84728,85112,85329,86227,86723,86074,85715,85725,85793,85339,86488,87271,87408,87041,87312,87924,88052,87649,87529,87685,87441,87251,87842,88382,88958,88437,88701,89503,89647,89299,89159,88730,89258,88610,88014,88299,88892,88472,88591,89900,90256,89138,89209,89279,88922,88712,89844,89792,90318,90451,90249,91247,91334,91113,90615,-(9),90525, 
# LNU01000002,53921,54036,54010,54035,54057,54927,55195,55070,54918,55507,55732,55493,55430,55154,55272,55413,55726,56356,56665,56375,56236,56488,56799,56359,56270,56348,56493,56414,56809,57305,57511,57172,56895,57077,56878,56778,56401,56613,56681,56945,56941,57809,57763,57299,57195,57609,57485,57397,57256,57450,57617,57625,57865,58867,59228,58667,58119,58174,58431,58397,57891,58033,57997,57946,58620,59403,59539,59155,58740,59275,59472,59473,59433,59767,59718,59656,60104,60566,60725,60614,60434,60711,60856,60359,60102,60337,60462,60603,60551,61053,61696,61250,61053,61539,61608,61072,60784,60985,61248,61062,61433,61917,62471,62123,62202,62579,62854,62624,62200,62321,62794,62426,62772,63245,63656,63311,63307,63321,63486,63589,63136,63355,63682,63043,63387,63854,63869,63839,63949,64090,64126,64242,64307,64484,64632,64403,64543,65195,65179,64900,64823,65138,65350,65309,65898,66057,66403,66357,66168,66614,66428,66020,66075,66369,66493,66750,66634,66876,67247,66517,66532,66935,66989,66530,66677,67006,67124,67113,66708,67420,67325,67132,67042,67520,67479,67396,67457,67679,67590,67610,67995,68036,68269,68130,68197,68955,68532,68327,67951,68396,68390,68089,67749,68140,68241,68112,68278,68716,68874,68333,68342,68696,68791,68785,68551,68699,68503,68826,69051,69342,69709,69390,69708,69998,69943,69734,69276,69538,69403,69540,69701,70494,70920,70438,70258,70745,70900,70856,70584,70535,70636,70164,70434,71203,71488,70952,71353,71339,71633,71534,71172,70988,71286,71344,71560,72150,72187,72092,71855,72240,72209,72122,71721,71846,71889,71956,71929,72780,72880,72192,71848,71812,71927,71450,71719,71706,71712,71898,71838,72098,72199,71993,72009,71977,72046,71653,71433,71275,71532,71544,71492,71781,71941,71732,72011,72007,71603,71354,72187,72505,72486,72276,72589,73017,72972,72586,72734,73064,72644,72715,72545,72547,72379,72538,72810,73253,73231,72861,72776,72656,72649,72423,72576,73073,73041,72741,73118,73147,73288,72867,72898,73541,73462,72721,73199,73173,73089,73196,73699,73822,73696,73393,73217,73741,74082,73807,73986,74227,74470,74164,74276,74345,74574,74384,74640,74791,74823,74505,74441,74893,75194,74967,74972,75366,75699,75230,75533,75228,75523,75048,74912,75688,75624,75314,75456,76289,76632,75697,76142,76642,76691,76654,76275,76737,76536,76069,76122,76705,76916,76864,77214,77752,77522,77507,77167,77638,76623,73010,74011,75454,75689,75366,75005,75589,75534,75373,74696,75254,75670,75268,75277,75939,76093,75714,75677,76138,76306,76357,76337,76453,76866,76409,76845,77089,77270,77321,76934,77068,76831,76973,77228,77796,77825,77784,78001,78407,78706,78750,78559,79045,78719,78051,78413,78986,79068,79011,78985,79107,79467,79626,79361,79290,79242,79034,79969,80323,80336,80200,79967,80095,80311,79921,80602,-(9),80943, 
# LNS11300001,76.2,76.2,75.9,76.2,76.2,76.2,76.2,76.5,76.2,76.1,76.1,76.0,76.4,76.3,76.3,76.5,76.3,76.7,76.5,76.5,76.1,76.5,76.4,76.4,76.7,76.6,76.6,76.4,76.4,76.3,76.3,76.3,76.1,76.2,76.3,76.3,76.0,75.9,76.1,76.0,75.8,75.8,75.8,75.6,75.8,75.6,75.5,75.4,75.7,75.6,75.8,75.8,76.1,76.2,76.0,76.0,75.9,75.6,75.6,75.5,75.4,75.4,75.6,75.4,75.6,75.7,75.7,75.7,75.2,75.3,75.1,75.0,75.3,75.1,74.9,74.9,74.8,74.7,74.8,75.0,75.0,75.2,75.2,75.4,75.4,75.4,75.3,75.3,74.9,75.0,74.9,74.8,75.0,74.7,74.6,74.6,74.6,74.9,74.9,74.9,75.0,75.0,75.2,74.8,75.0,75.1,74.9,74.8,74.9,74.9,75.0,75.1,75.0,75.0,75.0,75.0,74.9,74.9,75.1,74.9,74.9,74.8,74.8,74.8,74.9,74.9,75.0,74.6,75.0,74.9,75.0,74.9,75.0,74.9,74.7,74.6,74.8,74.7,74.7,74.6,74.6,74.6,74.6,74.8,75.1,75.3,75.0,74.9,74.8,74.8,74.5,74.8,74.6,74.5,74.6,74.7,75.0,74.8,74.7,74.6,74.4,74.3,74.4,74.1,74.5,74.4,74.3,74.3,74.0,74.2,74.1,74.2,74.5,74.2,74.1,74.1,74.4,74.0,73.7,73.6,73.5,73.7,73.3,73.6,73.6,73.6,73.4,73.3,73.6,73.4,73.6,73.5,73.7,73.2,73.2,73.1,73.1,73.3,73.5,73.4,73.2,73.3,73.5,73.2,73.0,73.2,73.2,73.4,73.5,73.4,73.4,73.5,73.3,73.2,73.2,73.2,73.4,73.5,73.6,73.5,73.5,73.4,73.1,73.4,73.4,73.4,73.5,73.7,73.8,73.6,73.5,73.4,73.2,73.3,73.1,72.8,73.0,72.9,73.1,73.1,73.4,73.1,73.1,72.9,73.1,73.0,73.1,72.9,72.9,72.9,72.7,72.5,72.4,72.4,72.1,72.3,72.4,72.2,72.0,72.0,71.7,71.6,71.5,71.0,71.2,71.2,71.4,71.8,71.4,71.1,71.2,71.3,71.1,70.8,70.9,70.7,70.5,70.5,70.4,70.5,70.5,70.4,70.3,70.5,70.5,70.4,70.5,70.5,70.2,70.2,70.2,70.1,70.2,70.3,70.2,69.9,70.1,70.3,70.1,70.1,70.3,70.0,69.7,69.9,69.9,69.9,69.8,69.6,69.8,69.2,69.5,69.2,69.2,69.0,69.4,69.0,69.1,69.2,69.3,69.4,69.2,69.2,69.2,69.3,69.3,69.2,69.1,69.3,69.4,69.0,69.0,69.0,68.8,68.8,68.7,69.0,68.9,69.2,69.3,69.3,69.0,69.3,69.3,69.3,69.3,69.2,69.0,69.0,69.1,69.2,69.1,69.2,69.0,69.1,69.0,69.1,69.3,69.0,68.9,69.0,69.0,69.3,69.2,69.3,69.3,69.2,68.9,68.8,68.8,68.9,68.9,69.0,69.1,69.0,69.0,68.9,69.1,69.2,69.4,69.2,69.2,69.2,69.3,69.2,69.2,69.1,68.4,66.1,66.7,67.3,67.3,67.7,67.5,67.8,67.5,67.4,67.4,67.2,67.1,67.5,67.6,67.6,67.8,67.8,67.8,67.8,67.9,67.8,67.8,68.1,68.1,67.9,68.0,67.8,67.7,67.9,68.1,68.1,68.0,68.1,68.0,68.1,68.3,68.1,68.1,68.1,68.0,68.2,68.2,67.9,68.4,68.1,67.9,67.8,68.0,67.9,67.8,68.1,68.1,67.9,68.1,68.1,67.9,67.9,68.0,67.6,67.8,68.1,67.8,67.8,67.6,68.0,67.8,-(9),67.8, 
# LNS11300002,56.4,56.5,56.4,56.4,56.1,56.4,56.5,56.6,56.6,56.8,57.2,57.2,57.5,57.1,57.2,57.3,57.3,57.3,57.4,57.5,57.5,57.4,57.8,57.5,57.7,57.6,57.6,57.5,57.7,57.4,57.5,57.6,57.6,57.4,57.4,57.3,57.3,57.4,57.3,57.6,57.4,57.4,57.2,57.2,57.4,57.5,57.5,57.5,57.7,57.7,57.8,57.9,57.8,57.9,58.1,58.0,57.8,57.6,57.8,57.9,57.7,57.7,57.6,57.7,58.0,58.0,57.9,58.0,57.9,58.1,58.2,58.4,58.7,58.8,58.7,58.8,58.9,58.7,58.6,58.9,58.9,58.9,58.9,58.7,58.8,58.8,58.8,59.2,58.8,58.7,59.1,59.0,59.0,59.2,59.1,58.9,58.9,58.9,59.0,59.1,59.1,59.0,59.3,59.3,59.5,59.6,59.8,59.8,59.6,59.5,59.8,59.7,59.8,59.7,60.0,59.9,60.0,59.8,59.8,60.1,59.9,59.9,59.9,59.7,59.7,59.7,59.7,59.8,60.0,60.0,59.9,60.0,60.1,60.0,59.9,60.1,59.9,60.1,60.0,60.0,60.0,60.1,60.2,60.1,60.1,60.0,60.1,60.3,60.0,60.0,59.9,59.6,59.8,59.7,59.9,59.9,60.1,60.0,60.2,59.8,59.7,59.7,59.7,59.5,59.6,59.7,59.8,59.7,59.5,59.9,59.7,59.7,59.6,59.6,59.5,59.6,59.7,59.6,59.5,59.5,59.7,59.6,59.7,59.7,59.7,59.9,59.5,59.5,59.1,59.3,59.2,59.0,59.1,59.2,59.3,59.2,59.3,59.3,59.3,59.0,59.0,59.0,59.0,59.1,59.1,59.1,59.0,59.2,59.3,59.2,59.2,59.3,59.4,59.5,59.3,59.2,59.1,59.3,59.2,59.2,59.2,59.5,59.6,59.5,59.3,59.4,59.5,59.5,59.5,59.4,59.4,58.9,59.1,59.3,59.3,59.2,59.5,59.2,59.4,59.4,59.5,59.3,59.5,59.4,59.6,59.5,59.4,59.6,59.4,59.6,59.5,59.5,59.4,59.5,59.5,59.4,59.4,59.5,59.4,59.2,58.9,58.8,58.9,58.6,58.8,58.9,58.8,58.9,58.8,58.5,58.4,58.6,58.5,58.4,58.6,58.3,58.3,58.1,58.3,58.3,58.1,58.0,58.0,58.1,58.3,58.1,58.0,57.8,57.7,57.8,57.8,57.6,57.7,57.7,57.6,57.6,57.6,57.7,57.6,57.7,57.5,57.3,57.2,57.3,57.3,57.4,57.3,57.3,57.1,56.8,56.9,57.0,57.0,57.2,57.2,57.0,57.1,56.9,56.9,56.9,56.8,57.1,57.0,56.7,56.9,56.6,56.6,56.7,56.9,56.8,56.6,56.7,56.4,56.6,56.8,56.8,56.9,56.8,57.1,56.9,56.8,56.6,56.6,56.8,56.8,56.8,56.7,56.7,56.9,57.0,57.2,57.2,57.1,57.0,57.2,57.1,57.2,56.8,57.0,56.8,56.7,57.1,56.9,56.9,56.9,57.2,57.4,56.9,57.1,57.3,57.3,57.4,57.5,57.6,57.4,57.1,57.1,57.2,57.2,57.4,57.6,57.7,57.6,57.8,57.8,58.0,57.1,54.6,55.2,56.0,56.1,56.0,55.7,56.0,56.0,56.0,55.7,55.9,56.2,56.0,55.9,56.1,56.1,56.0,56.0,56.1,56.3,56.6,56.8,56.6,56.9,56.7,56.9,56.8,56.8,57.0,56.8,56.6,56.5,56.8,57.1,57.2,57.2,57.3,57.3,57.3,57.4,57.6,57.5,57.6,57.4,57.1,57.5,57.6,57.6,57.7,57.5,57.3,57.5,57.7,57.6,57.3,57.3,57.4,57.5,57.5,57.5,57.5,57.2,57.0,57.1,56.9,57.4,-(9),57.4, 
# LNU02048984, , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , ,4333,4417,4431,4397,4310,4395,4544,4545,4621,4484,4529,4497,4495,4437,4306,4183,4259,4402,4454,4533,4572,4614,4560,4607,4650,4585,4497,4517,4523,4679,4746,4585,4526,4590,4639,4753,4838,4877,4999,5060,4995,5118,5031,4908,4907,4827,4989,4923,4992,4993,5151,5226,5224,5304,5266,5328,5222,5120,5049,4936,5010,5088,5350,5443,5426,5299,5216,5206,5105,5199,5303,5398,5541,5550,5501,5514,5397,5485,5453,5417,5382,5453,5590,5701,5720,5864,5700,5648,5713,5701,5602,5742,5690,5803,5835,5810,5705,5782,5830,5734,5797,5711,5682,5827,5777,5878,5872,5814,5599,5560,5640,5482,5458,5316,5362,5390,5368,5522,5372,5520,5483,5356,5446,5124,5135,5254,5132,4995,5036,5037,5037,5263,5208,5221,5169,5030,5232,5155,5170,5101,4950,5030,5060,5199,5191,5226,5130,5258,5419,5206,5256,5366,5263,5383,5160,5175,5244,5246,5419,5342,5305,5170,5187,5318,5310,5423,5330,5433,5452,5385,5462,5384,5396,5302,5324,5294,5400,5507,5585,5666,5483,5425,5514,5378,5457,5555,5453,5176,5534,5283,5692,5842,5796,5793,5567,5518,5476,5586,5468,5342,5734,5704,5898,5835,5713,5681,5740,5861,5742,5611,5752,5829,5974,6171,6021,6047,5958,5767,5891,5787,5696,5586,5545,5768,5840,6057,6226,6085,5965,6072,5991,6094,6061,6195,6225,6149,6227,6358,6299,6554,6472,6467(C),6287(C),6410(C),6249,6208,6279(C),6327,6275,6315,6236,5859,5938,5670,6024,6196,6063,6210,6144,6091,6146,6334,6363,6213,6366,6291,6322,6678,6823,6659,6643,6672,6710,6851,7028,6811,6560,6435,6285,6404,6706,6836,7158,6989,6684,6626,6872,6637,6656,6565,6637,6686,6787,6974,6911,6911,7174,6873,6834,6850,6821,6911,6860,6980,6695,7052,6761,6979,7164,-(9),7140, 
# LNS12027714,9657,9781,9777,9928,10241,9911,9911,9953,9999,9786,10120,9939,10093,9985,9984,10055,9921,9976,10043,10081,10004,9995,9894,10034,10104,10007,10126,10100,10143,10140,10047,10038,10008,10124,10051,10282,10171,10232,10225,10647,10070,10298,10268,10284,10327,10345,10310,10132,9936,9971,9939,9856,9839,9888,9975,10010,10047,10003,10033,10076,10179,10239,10118,10292,10448,10402,10363,10283,10248,10236,10318,10267,10594,10806,10689,10713,10760,10574,10563,10727,10597,10502,10617,10671,10643,10607,10470,10494,10415,10388,10578,10452,10462,10503,10371,10438,10441,10554,10605,10525,10351,10484,10502,10430,10322,10552,10490,10632,10854,10583,10722,10530,10540,10487,10347,10413,10381,10364,10519,10441,10337,10209,10118,10329,10408,10433,10428,10262,10354,10285,10275,10180,10119,10061,10059,10155,10063,10249,10143,10292,9974,10116,9911,9879,10298,10379,10341,10384,10349,10268,10174,10222,10337,9954,9824,10015,10088,10214,10393,10185,10134,10241,10132,9995,10101,10032,9833,9944,9647,9748,9755,9821,9851,9758,9861,9888,10072,10118,10282,10324,10396,10190,10144,10157,10052,10240,10236,10416,10335,10393,10541,10470,10460,10348,10062,10166,10325,10335,10529,10679,10476,10656,10584,10561,10516,10568,10638,10912,10574,10364,10454,10145,10334,10380,10322,10417,10628,10633,10588,10539,10501,10467,10426,10507,10603,10684,10653,10860,10539,10456,10642,10511,10479,10547,10484,10330,10386,10261,10219,10134,10227,10256,10070,10170,10180,10216,10421,10139,9995,9747,9699,9841,9726,9838,10065,9926,9828,9789,9749,9908,9830,9663,9774,9858,9735,9925,9778,9756,9764,9698,9645,9596,9553,9696,9493,9511,9679,9597,9614,9506,9507,9363,9312,9428,9143,9409,9382,9461,9567,9284,9336,9338,9491,9618,9622,9493,9605,9562,9705,9731,9486,9416,9044,9387,9434,9499,9754,9542,9422,9275,9287,9352,9307,9406,9300,9246,9105,9157,9204,9269,9541,9688,9577,9540,9577,9169,9491,9585,9979,9564,9683,9637,9218,9406,9432,9346,9559,9613,9794,9796,9715,9607,9440,9530,9429,9482,9502,9773,9320,9720,9617,9487,9404,9603,9109,9253,9537,9705,9776,9778,9860,9806,9905,9838,9746,9411,9564,9503,9708,9632,9696,9822,9685,9554,9423,9264,9380,9500,9671,9590,9599,9610,9625,9575,9508,9534,9433,8245,8658,9075,9148,9502,9472,9576,9463,9439,9577,9488,9829,9681,9996,9883,10315,10241,10158,10217,10032,10029,9859,9917,9957,9876,10083,10034,9766,9651,9862,9982,9707,9792,9932,10066,9773,9794,9394,9632,9530,9505,9742,9666,9732,10001,9786,10016,10156,9943,10051,9688,9837,10090,9845,9839,9823,9964,9827,9700,9794,9947,10013,9675,9613,9917,9731,-(9),10257, 
# LNU02374597, , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , ,19.6,20.6,20.6,21.0,20.6,20.5,20.2,20.0,19.8,19.8,19.9,19.7,19.4,19.5,18.4,18.4,18.1,18.4,18.6,18.5,18.9,19.4,18.8,19.1,18.6,18.0,18.6,18.4,18.2,18.4,18.0,17.4,17.4,17.7,17.7,17.8,17.7,17.6,17.7,17.7,18.5,18.1,17.9,17.4,16.8,17.1,17.8,18.1,17.7,17.9,18.0,18.2,18.7,18.1,18.1,18.0,18.1,18.0,18.0,17.9,17.4,17.3,17.6,18.2,17.5,17.1,16.5,15.8,16.4,16.7,16.7,17.0,16.8,17.0,17.2,17.6,17.7,17.6,18.0,17.3,17.6,17.5,17.3,17.8,18.1,17.7,17.5,17.2,17.3,16.8,17.2,17.4,17.1,17.8,18.2,18.5,18.1,18.1,17.6,18.1,18.0,18.0,18.3,17.4,18.3,18.3,18.0,18.6,18.9,18.8,18.8,19.6,19.4,19.0,19.1,18.6,18.9,19.7,19.2,18.7,18.6,18.5,19.2,19.9,19.9,19.4,19.0,18.7,19.0,19.8,19.4,19.3,19.2,19.2,19.8,19.3,19.1,19.3,19.0,18.8,19.1,19.3,16.1,16.7,17.5,17.3,17.9,17.8,18.3,17.9,17.8,17.2,17.4,18.1,18.4,18.5,19.0,18.7,19.2,20.3,20.4,21.5,20.6,20.7,20.7,21.1,21.2,21.3,21.2,20.8,20.8,21.5,22.0,22.3,22.4,22.4,22.1,21.9,21.6,22.4,22.4,22.9,23.0,22.5,22.6,22.9,22.9,22.9,22.5,22.4,23.0,23.1,22.5,22.2,21.9,22.7,22.7,23.3,22.9,22.7,22.2,22.0,22.2,22.7,22.7,22.3,22.9,22.8,-(9),24.4, 
# LNS12300000,62.0,62.1,61.9,62.2,62.0,62.3,62.3,62.4,62.4,62.5,62.7,62.6,62.9,62.9,62.9,62.9,62.9,63.0,63.0,63.1,62.8,62.9,63.0,63.0,63.2,63.2,63.2,63.0,63.1,62.9,62.8,62.7,62.5,62.5,62.3,62.2,62.0,61.9,61.8,62.0,61.6,61.7,61.6,61.5,61.6,61.5,61.4,61.2,61.5,61.3,61.5,61.6,61.5,61.5,61.6,61.6,61.4,61.3,61.4,61.4,61.4,61.4,61.5,61.5,61.7,61.8,61.8,62.0,61.7,61.8,61.9,62.0,62.2,62.3,62.1,62.3,62.5,62.3,62.3,62.6,62.7,62.9,63.0,63.1,63.0,63.1,63.1,63.1,62.7,62.7,62.8,62.8,62.9,62.9,62.8,62.7,62.7,62.9,63.0,63.0,63.0,63.2,63.3,63.3,63.4,63.5,63.4,63.4,63.4,63.4,63.6,63.7,63.8,63.7,63.9,63.9,63.9,63.9,64.1,64.0,64.0,64.0,64.0,64.1,64.1,64.0,64.0,63.9,64.2,64.1,64.2,64.3,64.4,64.2,64.2,64.2,64.3,64.2,64.2,64.2,64.2,64.3,64.4,64.4,64.6,64.6,64.6,64.7,64.4,64.5,64.2,64.2,64.2,64.2,64.3,64.4,64.4,64.3,64.3,64.0,63.8,63.7,63.7,63.2,63.5,63.2,63.0,62.9,62.7,63.0,62.8,62.7,62.9,62.7,62.7,62.7,63.0,62.7,62.5,62.4,62.5,62.5,62.4,62.4,62.3,62.3,62.1,62.1,62.0,62.1,62.3,62.2,62.3,62.3,62.2,62.3,62.3,62.4,62.5,62.4,62.3,62.3,62.5,62.4,62.4,62.4,62.4,62.7,62.8,62.7,62.8,62.9,62.8,62.8,62.7,62.8,62.9,63.0,63.1,63.0,63.1,63.1,63.0,63.1,63.1,63.3,63.3,63.4,63.3,63.3,63.3,63.0,63.0,63.0,62.9,62.7,62.9,62.7,62.9,62.7,62.9,62.8,62.7,62.7,62.5,62.4,62.2,62.0,61.9,61.7,61.4,61.0,60.6,60.3,59.9,59.8,59.6,59.4,59.3,59.1,58.7,58.5,58.6,58.3,58.5,58.5,58.5,58.7,58.6,58.5,58.5,58.6,58.5,58.3,58.2,58.3,58.3,58.4,58.4,58.4,58.3,58.2,58.2,58.3,58.4,58.4,58.6,58.6,58.4,58.5,58.5,58.4,58.5,58.6,58.5,58.4,58.7,58.8,58.7,58.7,58.6,58.6,58.5,58.6,58.6,58.6,58.7,58.7,58.7,58.3,58.6,58.7,58.8,58.7,58.9,58.9,58.9,59.0,59.0,59.0,59.1,59.3,59.2,59.3,59.3,59.2,59.2,59.3,59.4,59.4,59.3,59.4,59.2,59.3,59.4,59.6,59.7,59.8,59.8,59.7,59.7,59.7,59.8,59.8,59.7,59.7,59.7,59.7,59.9,60.0,60.2,60.2,60.1,60.1,60.2,60.1,60.4,60.1,60.1,60.1,60.1,60.4,60.4,60.4,60.5,60.5,60.6,60.3,60.4,60.5,60.6,60.6,60.6,60.7,60.6,60.5,60.6,60.7,60.8,60.8,61.0,61.0,61.0,61.1,61.1,61.1,59.8,51.2,52.7,54.7,55.2,56.5,56.6,57.5,57.4,57.4,57.4,57.6,57.7,57.9,58.0,58.1,58.4,58.6,58.8,59.0,59.4,59.5,59.7,59.8,60.1,59.9,60.1,59.9,59.9,60.1,60.1,60.0,59.9,60.1,60.2,60.3,60.4,60.4,60.3,60.3,60.4,60.4,60.4,60.2,60.4,60.1,60.2,60.1,60.3,60.2,60.1,60.0,60.0,60.0,60.1,60.0,59.8,60.0,60.1,59.9,59.9,60.0,59.7,59.7,59.6,59.6,59.7,-(9),59.6, 
# LNS17800000, , , , , , , , , , , , , , , , , , , , , , , , , ,3583,3367,3495,3125,3389,3297,3106,3356,3236,3308,3185,3237,3022,3082,2958,3356,3170,3156,3082,2958,3086,3000,3011,2934,2978,2949,2869,3154,2990,2970,3083,3152,3311,3043,3111,3187,3235,3057,3228,3028,2988,3027,3105,3435,3011,3088,3178,3077,3531,3592,3131,3192,3341,3315,3139,3196,3229,3300,3532,3317,3093,3303,3392,3545,3424,3252,3396,3292,3376,3452,3243,3174,3234,3251,3162,3198,3225,3314,3408,3115,3229,3227,3106,3357,3396,3336,3332,3328,3353,3157,3282,3369,3303,3309,3567,3453,3377,3432,3463,3417,3620,3531,3887,3590,3760,3677,3629,3665,3740,3722,3736,3693,3730,3851,3811,3779,3656,3666,3707,3591,3739,3798,3547,3992,3696,3921,3684,3901,3929,3894,3748,3894,4170,3836,4193,4163,3958,4028,4523,3839,3890,3719,3883,3897,3419,3992,3801,3817,3988,3721,3682,3413,3956,4040,3701,3705,3710,3790,3608,3667,3801,4074,3781,3894,3768,3822,3991,3766,3747,3910,3845,3846,3604,3887,3946,4006,4014,3815,4119,3978,3890,3847,3863,3894,3863,3993,3875,3934,4044,4037,4095,3935,3791,4011,4229,4132,4136,4244,4086,4154,3904,4175,4137,4283,4333,4191,4502,3961,4035,3998,4412,3685,4277,3772,4160,3630,4048,3957,3886,3819,4031,3974,3756,3944,3701,3867,3797,4038,3576,3789,3667,3461,3611,3499,3759,3839,3591,3421,3867,3450,3583,3728,3467,3824,3560,3562,3519,3552,3997,3603,3699,3668,3679,3485,3564,3742,3825,3825,3500,3493,3772,3675,3937,3945,3562,3656,3975,3686,3716,3893,4067,3486,3734,4058,3743,3641,4120,4104,3903,3879,4021,3892,3998,3962,4439,3453,3922,4009,4114,4016,4053,4012,3935,3860,3970,4200,4154,4151,4352,4287,4647,4457,4280,4442,4839,4424,4715,4503,4350,4388,4156,4566,4381,4279,4437,4432,4253,4178,4267,4451,4401,4628,4607,4378,4429,4350,4591,4781,4598,4608,4499,4450,5245,4700,4579,4667,4210,4591,4680,4320,4589,4674,5356,4453,4525,4622,4766,4594,4696,4855,4806,4669,4542,4591,4665,4507,4557,4660,4727,4703,4454,5952,9433,4439,3504,4198,3973,4564,4094,4814,4593,4453,4429,4381,4544,4810,4640,4373,4854,4602,4988,4420,4608,4576,4706,4432,5042,4736,5117,4684,4863,4851,4869,4945,4721,4738,4974,4514,4872,4602,4705,4910,4547,4802,4856,4501,4897,4478,4762,4551,4432,4893,4789,4171,4403,4324,4434,4687,4231,4374,4801,4629,4446,5417,4787,4618,4723,4787,-(9),-(9), 
# LNS17400000, , , , , , , , , , , , , , , , , , , , , , , , , ,1823,1764,1873,1676,1771,1941,1877,1752,1902,2034,1874,1978,2084,2130,1956,2077,1909,1947,2043,1959,2019,1935,1975,2150,2035,1773,1915,2028,2057,1940,1950,2087,1923,1994,2019,1818,1903,1930,1894,1895,1872,1925,1807,1852,1852,1807,1932,1884,1898,1852,1898,1776,1875,1910,1848,1783,1606,1791,1867,1969,1700,1829,1873,1784,1871,1820,1910,1895,1857,1798,1657,1867,1677,1752,1750,1787,1754,1765,1634,1792,1666,1849,1604,1863,1789,1650,1724,1639,1865,1685,1578,1667,1691,1596,1880,1685,1750,1781,1586,1656,1661,1739,1684,1758,1684,1643,1751,1576,1736,1591,1682,1685,1662,1611,1603,1527,1613,1613,1620,1614,1678,1646,1532,1688,1597,1751,1718,1643,1549,1444,1472,1758,1729,1782,1827,1810,1877,1833,1946,1823,2025,2109,1986,2130,1950,1884,2008,1797,1989,1935,1934,1878,2004,2050,1911,2008,1886,1959,1978,2000,1949,1882,2041,1931,1733,1832,1922,1729,1806,1857,1787,1851,1777,1823,1858,1907,1890,1801,1848,1814,1853,1730,1692,1738,1822,1783,1769,1853,1736,1685,1732,1595,1692,1728,1882,1754,1752,1900,1725,1761,1749,1814,1820,1917,1833,1701,1763,1712,1774,1843,1714,1795,1818,1725,1866,1780,1817,2005,1915,2054,1996,1967,2288,2140,2259,2506,2519,2755,2834,2647,2484,2649,2550,2463,2560,2621,2516,2294,2373,2228,2341,2310,2274,2349,2164,2296,2396,2231,2232,2601,2206,2152,2043,2132,2268,2212,2135,2105,2016,2408,2123,2139,2093,1956,1989,2104,1994,1950,2024,2116,2059,1943,1972,1959,2204,2144,1824,1917,2013,1930,2092,1900,1947,1910,2198,1550,1767,2016,1994,1903,1797,1937,1834,1886,1991,1697,1723,1948,1752,1791,1837,1794,1830,1847,1697,1663,1672,1783,1678,1731,1786,1585,1592,1789,1782,1769,1785,1661,1711,1732,1721,1795,1716,1643,1731,1584,1682,1641,1713,1649,1735,1615,1644,1597,1616,1462,1523,1694,1617,1417,1492,1547,1625,1516,1546,1499,1544,1459,1444,1527,1337,1400,1577,1418,1363,1363,1515,1316,1506,1625,1512,2759,17455,4859,3741,3353,1908,2497,2019,2024,2285,2047,1930,1828,2016,1730,1789,1710,1599,1519,1414,1577,1276,1684,1638,1570,1676,1549,1496,1554,1510,1425,1613,1623,1505,1398,1442,1398,1420,1654,1444,1397,1512,1565,1550,1464,1524,1474,1546,1513,1707,1536,1561,1799,1770,1593,1640,1352,1483,1450,1699,1636,1545,1799,1684,1741,1595,1734,-(9),-(9), 
# LNS13025670,1.4,1.4,1.4,1.3,1.4,1.3,1.3,1.3,1.3,1.3,1.2,1.2,1.2,1.1,1.1,1.1,1.1,1.0,1.2,1.0,1.1,1.1,1.1,1.1,1.1,1.1,1.1,1.1,1.1,1.1,1.2,1.3,1.3,1.3,1.5,1.4,1.5,1.6,1.7,1.7,1.8,2.0,1.9,2.0,2.0,2.1,2.1,2.3,2.4,2.5,2.5,2.4,2.7,2.9,2.8,2.8,2.7,2.7,2.6,2.8,2.6,2.5,2.4,2.3,2.4,2.4,2.4,2.3,2.4,2.3,2.3,2.3,2.3,2.4,2.3,2.2,2.2,2.1,2.2,2.1,2.1,2.2,2.0,1.9,1.8,1.8,1.7,1.9,2.0,1.7,1.7,1.8,1.7,1.7,1.8,1.8,1.8,1.7,1.8,1.8,1.8,1.8,1.7,1.7,1.7,1.7,1.6,1.6,1.6,1.6,1.6,1.6,1.6,1.5,1.6,1.5,1.5,1.4,1.3,1.4,1.3,1.3,1.3,1.1,1.1,1.2,1.1,1.2,1.2,1.1,1.1,1.1,1.1,1.1,1.1,1.1,1.1,1.2,1.1,1.0,1.0,1.0,1.0,1.0,1.0,0.9,0.9,0.9,0.9,0.9,0.9,1.0,0.9,0.9,0.9,0.9,1.0,1.0,1.1,1.0,1.0,1.1,1.2,1.3,1.4,1.4,1.6,1.7,1.8,1.8,1.9,2.0,2.0,2.1,2.0,2.0,2.0,2.1,2.1,2.3,2.2,2.2,2.2,2.3,2.3,2.4,2.5,2.4,2.4,2.4,2.3,2.3,2.3,2.2,2.3,2.0,2.1,2.1,2.0,1.9,2.0,2.1,2.0,2.0,1.9,2.0,1.9,1.8,1.8,1.6,1.6,1.7,1.7,1.7,1.7,1.6,1.5,1.7,1.6,1.6,1.5,1.4,1.5,1.5,1.5,1.4,1.4,1.4,1.4,1.4,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.6,1.6,1.6,1.6,1.7,1.8,1.9,2.0,2.2,2.3,2.6,2.5,2.9,3.1,3.5,3.8,4.1,4.5,5.1,5.1,5.1,5.5,5.6,5.7,5.8,5.8,5.8,5.9,5.9,5.8,5.8,5.7,5.5,5.5,5.6,5.6,5.6,5.5,5.3,5.3,5.2,5.3,5.3,5.3,5.4,5.4,5.1,5.0,4.9,4.8,4.7,4.6,4.6,4.6,4.7,4.5,4.5,4.4,4.4,4.2,4.3,4.2,4.2,4.1,4.1,4.1,4.0,3.9,3.8,3.8,3.7,3.7,3.6,3.4,3.5,3.5,3.2,3.1,3.0,3.0,2.9,2.8,2.7,2.7,2.6,2.6,2.5,2.4,2.3,2.4,2.3,2.2,2.2,2.1,2.1,2.1,2.1,2.0,2.1,2.1,2.1,1.9,2.0,2.0,1.9,2.0,2.0,1.9,1.9,1.9,1.8,1.7,1.7,1.7,1.6,1.7,1.7,1.7,1.6,1.6,1.5,1.5,1.4,1.3,1.4,1.3,1.4,1.5,1.4,1.4,1.4,1.3,1.4,1.3,1.3,1.3,1.2,1.3,1.3,1.3,1.3,1.3,1.3,1.3,1.2,1.3,1.2,1.2,1.1,1.4,2.0,5.0,5.1,4.6,3.9,3.6,3.4,3.4,3.4,3.5,3.3,3.1,3.3,2.9,2.7,2.3,2.1,1.9,1.7,1.5,1.5,1.2,1.2,1.2,1.3,1.1,1.2,1.2,1.2,1.2,1.1,1.2,1.1,1.1,1.1,1.2,1.2,1.3,1.4,1.4,1.4,1.3,1.4,1.3,1.3,1.3,1.3,1.4,1.5,1.6,1.6,1.6,1.7,1.7,1.6,1.5,1.5,1.5,1.6,1.5,1.6,1.8,1.7,1.8,-(9),1.8, 
# LNS15000000,62853,62813,63198,62981,63303,63089,63064,62705,63002,62908,62607,62780,62254,62642,62670,62459,62707,62334,62516,62432,62782,62660,62380,62668,62580,62806,62829,63129,63020,63485,63456,63352,63636,63715,63802,63875,64208,64251,64143,63969,64474,64469,64792,64966,64652,64855,64956,65134,64692,64860,64600,64513,64384,64204,64263,64405,64728,65416,65180,65230,65562,65650,65650,65814,65285,65308,65485,65444,65991,65871,65914,65853,65357,65421,65813,65742,65731,66132,66207,65768,65827,65686,65716,65814,65715,65770,65899,65558,66435,66504,66272,66465,66394,66476,66741,66997,67018,66820,66741,66692,66611,66762,66357,66793,66546,66352,66456,66523,66829,66988,66622,66658,66713,66789,66689,66746,66895,67134,66980,66943,67143,67288,67311,67581,67527,67630,67682,67910,67413,67640,67723,67635,67715,67906,68306,68277,68320,68304,68390,68609,68642,68712,68641,68655,69142,69120,69338,69267,69853,69876,70398,70401,70645,70782,70579,70488,70088,70409,70381,70956,71414,71592,71526,72136,71676,71817,71876,72010,72623,72010,72343,72281,72260,72600,72827,72856,72554,73026,73508,73675,73960,74015,74295,74066,74268,73958,74767,75062,75249,75324,75280,75780,75319,75648,75606,75907,75903,75735,75730,76113,76526,76399,76259,76581,76808,76677,76846,76514,76409,76673,76721,76642,76739,76958,77138,77394,77339,77122,77161,77318,77359,77317,77535,77451,77757,77634,77499,77376,77506,77851,77982,78818,78810,78671,78904,79461,79047,79532,79105,79238,78554,79156,79087,79429,79102,79314,79395,79466,79790,79736,80189,80380,80529,80374,80953,80762,80705,80938,81367,81780,82495,82766,82865,83813,83349,83304,83206,82707,83409,84075,84199,84014,84347,84895,84590,85240,85441,85637,85623,85603,85834,86144,86383,86111,85940,86308,86312,86589,87888,87765,87855,88239,88100,88073,88405,88803,88613,88429,88836,88722,88900,89516,89990,89780,89827,89803,90156,90355,90481,91708,91302,91563,91563,91603,91230,92070,91938,92107,92016,92099,92406,92240,92350,92695,92694,93256,93437,93205,92804,93601,93880,93924,94592,94374,94284,93901,94117,93937,93589,93828,94390,94430,94426,94292,94377,94716,95034,95064,94462,94386,94277,94243,94699,94766,94689,94771,94423,95457,95370,95574,95866,95156,95411,95501,95606,95433,95502,96406,96202,95913,95871,95682,95277,95393,95633,96107,96110,95870,95635,95658,95546,95429,95524,95483,95124,95161,97200,103627,101945,100210,100241,99852,100569,99922,100456,100485,100763,100734,100603,100260,100410,100142,99966,100084,100271,100154,99747,99639,99576,99425,99224,99666,99317,99789,99985,99530,99753,99888,100258,99819,99998,99754,99621,99719,99733,99864,99899,99455,99660,99952,99682,100552,100201,100237,99963,100078,100449,100434,100329,100360,100377,100861,101159,101091,101941,102487,102431,102062,102875,103204,103443,103223,102978,-(9),103061, 
# LNS15026639, , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , ,6723,6315,6387,6636,6363,6082,6278,6019,6014,5858,5890,5945,5790,5746,5837,5484,5719,5602,5501,5563,5655,5704,5587,5852,5599,5689,5515,5500,5456,5591,5375,5461,5350,5394,5300,5128,5045,5146,5069,4893,5200,4923,4914,4819,4836,4772,4852,4766,4930,4812,4900,4891,4691,4792,4852,4951,4915,4862,4568,4550,4706,4638,4631,4778,4635,4797,4517,4533,4350,4310,4428,4394,4302,4458,4689,4428,4385,4313,4430,4290,4389,4393,4332,4551,4401,4571,4297,4509,4516,4637,4489,4900,4577,4691,4751,4737,4803,4559,4598,4609,4825,4766,4847,4627,4687,4429,4733,4567,4632,4600,4916,4451,4810,4740,4855,4830,4832,4760,4534,4695,4769,4750,4816,4690,4741,4648,4661,4933,4930,5277,5113,4949,4992,4968,5018,5114,4771,5222,4947,4813,4990,4993,4818,5183,4964,4901,4918,4719,4635,4726,4862,4951,4666,4868,4818,4390,4506,4706,4565,4794,4968,4857,4737,4827,4750,4352,4648,4657,4846,4739,4718,4733,4851,4929,5023,4922,5153,5094,5421,5431,5708,5617,5807,5927,5986,5908,6003,5649,5949,6002,5998,6186,5942,6098,5993,5913,5824,5909,5895,6037,6270,6289,6182,6431,6472,6390,6527,6537,6289,6519,6513,6463,6262,6384,6538,6323,6343,6335,6302,6426,6309,6564,6516,7011,6817,6551,6833,6728,6637,6772,6670,6428,6726,6614,6526,6284,6119,6024,5754,6126,6360,6011,6174,6207,6553,6207,6264,6376,6326,6431,6558,6406,6300,6503,6355,6221,6051,6130,6097,5890,5868,5997,5649,5909,6006,5927,5730,5812,5962,5590,5906,5752,6017,5948,5864,5668,5758,5653,5758,5708,5465,5277,5425,5734,5637,5293,5219,5275,5201,5208,5047,5151,5189,5203,5168,5419,5263,5393,5392,5341,5279,5282,5178,5095,4980,5264,4970,5215,4788,4755,4852,4853,4942,5075,5529,9904,8890,8204,7671,7067,7105,6654,7130,7295,6960,7015,6898,6607,6550,6448,6479,5695,5820,5900,5832,5736,5702,5425,5836,5850,5636,5685,5880,5517,5750,5667,5555,5162,5292,5118,4992,5282,5454,5439,5235,5365,5395,5361,5354,5677,5783,5675,5461,5639,5706,5256,5607,5632,5683,5652,5483,5505,5479,5893,5915,5672,5991,6030,6175,6354,5933,-(9),6136, 
# '''

In [72]:
# # Series stored as a dictionary
# series = {'LNS12300061': 'PA_EPOP_M', 
#           'LNS12300062': 'PA_EPOP_W',
#           'LNS12005054': 'avghrstot',
#           'LNU02033699': 'avghrsserv',
#           'LNU02033232': 'avghrsptecon',
#           'LNU01000000': 'LFnsa',
#           'LNS12026619': 'MJHsa',
#           'LNU02000000': 'EMP',
#           'LNS12000000': 'EMPsa',
#           'LNU00000001': 'MenPop',
#           'LNU00000002': 'WomenPop',
#           'LNU01000001': 'MenLF',
#           'LNU01000002': 'WomenLF',
#           'LNS11300001': 'MenLFPR',
#           'LNS11300002': 'WomenLFPR',
#           'LNU02048984': 'seinc',
#           'LNS12027714': 'seuninc',
#           'LNU02374597': 'empdis',
#           'LNS12300000': 'EPOP',
#           'LNS17800000': 'E_NILF',
#           'LNS17400000': 'E_UNEMP',
#           'LNS13025670': 'U1',
#           'LNS15000000': 'NILF_Level',
#           'LNS15026639': 'NILF_WantJob'}

# d = pd.read_csv(io.BytesIO(data)).T
# d.columns = d.iloc[0]
# d = d.iloc[1:]
# d.index = pd.to_datetime(d.index)
# d.loc[pd.to_datetime('2025-11-01'), ['LNS17800000', 'LNS17400000']] = d.loc['2025-09-01', ['LNS17800000', 'LNS17400000']]
# d.loc[pd.to_datetime('2025-10-01')] = (d.loc['2025-09-01'].astype('float') + 
#                                        d.loc['2025-11-01'].astype('float')) / 2
# d = d.replace('\(C\)', '', regex=True).replace('\(1\)', '', regex=True)
# d = d.rename(series, axis=1).replace(' ', None).astype('float').dropna(how='all')
# d.to_csv(data_dir / 'jobs_report_main2.csv', index_label='date')

<>:34: SyntaxWarning: invalid escape sequence '\('
<>:34: SyntaxWarning: invalid escape sequence '\('
<>:34: SyntaxWarning: invalid escape sequence '\('
<>:34: SyntaxWarning: invalid escape sequence '\('
/tmp/ipykernel_71202/2427968002.py:34: SyntaxWarning: invalid escape sequence '\('
  d = d.replace('\(C\)', '', regex=True).replace('\(1\)', '', regex=True)
/tmp/ipykernel_71202/2427968002.py:34: SyntaxWarning: invalid escape sequence '\('
  d = d.replace('\(C\)', '', regex=True).replace('\(1\)', '', regex=True)
/tmp/ipykernel_71202/2427968002.py:30: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  d.index = pd.to_datetime(d.index)

In [3]:
# Series stored as a dictionary
series = {'LNS12300061': 'PA_EPOP_M', 
          'LNS12300062': 'PA_EPOP_W',
          'LNS12005054': 'avghrstot',
          'LNU02033699': 'avghrsserv',
          'LNU02033232': 'avghrsptecon',
          'LNU01000000': 'LFnsa',
          'LNS12026619': 'MJHsa',
          'LNU02000000': 'EMP',
          'LNS12000000': 'EMPsa',
          'LNU00000001': 'MenPop',
          'LNU00000002': 'WomenPop',
          'LNU01000001': 'MenLF',
          'LNU01000002': 'WomenLF',
          'LNS11300001': 'MenLFPR',
          'LNS11300002': 'WomenLFPR',
          'LNU02048984': 'seinc',
          'LNS12027714': 'seuninc',
          'LNU02374597': 'empdis',
          'LNS12300000': 'EPOP',
          'LNS17800000': 'E_NILF',
          'LNS17400000': 'E_UNEMP',
          'LNS13025670': 'U1',
          'LNS15000000': 'NILF_Level',
          'LNS15026639': 'NILF_WantJob'}

# Start year and end year
dates = (1988, 2025)
df = bls_api(series, dates, bls_key)
df.to_csv(data_dir / 'jobs_report_main2.csv', index_label='date')

Post Request Status: REQUEST_SUCCEEDED

In [16]:
# df = pd.read_csv(data_dir / 'jobs_report_main.csv', index_col='date', 
#                  parse_dates=True)
# df2 = pd.read_csv(data_dir / 'jobs_report_main2.csv', index_col='date', 
#                  parse_dates=True)

In [20]:
# df.iloc[-2]

White                        3.9
Black                        8.2
Hispanic                     5.0
Total                        4.5
U6                           8.7
Level                     7781.0
WantJob                   5774.0
LT                        1862.0
MT                        2978.0
POP                     274633.0
PA_EPOP                     80.6
Job Loser                 3560.0
Temporary Layoff          1002.0
Permanent Separation      1936.0
Job Leaver                 861.0
Re-entrant                2600.0
New entrant                774.0
Median                       9.8
Mean                        23.1
NILF                         NaN
UNEMP                        NaN
LF                      171541.0
PTECON                    5487.0
PTNONECON                23068.0
Asian                        3.6
Name: 2025-11-01 00:00:00, dtype: float64

In [22]:
# October/November 2025 missing data
df = pd.read_csv(data_dir / 'jobs_report_main.csv', index_col='date', 
                 parse_dates=True)
s = ['NILF', 'UNEMP']
df.loc[pd.to_datetime('2025-11-01'),s] = df.loc['2025-09-01',s]
df.loc[pd.to_datetime('2025-12-01'),s] = df.loc['2025-09-01',s]
df.loc[pd.to_datetime('2025-10-01')] = (df.loc['2025-09-01'] + df.loc['2025-11-01']) / 2
df.to_csv(data_dir / 'jobs_report_main.csv', index_label='date')

# DF2
df = pd.read_csv(data_dir / 'jobs_report_main2.csv', index_col='date', 
                 parse_dates=True)
s = ['E_NILF', 'E_UNEMP']
df.loc[pd.to_datetime('2025-11-01'),s] = df.loc['2025-09-01',s]
df.loc[pd.to_datetime('2025-12-01'),s] = df.loc['2025-09-01',s]
df.loc[pd.to_datetime('2025-10-01')] = (df.loc['2025-09-01'] + df.loc['2025-11-01']) / 2
df.to_csv(data_dir / 'jobs_report_main2.csv', index_label='date')

### Unemployment rate

In [27]:
df = pd.read_csv(data_dir / 'jobs_report_main.csv', index_col='date', 
                 parse_dates=True)
df2 = pd.read_csv(data_dir / 'jobs_report_main2.csv', index_col='date', 
                 parse_dates=True)[['U1']]
df = pd.concat([df, df2], axis=1)
srs = ['Total', 'U6', 'U1']
dft = pd.concat([df[srs].resample('QS').mean().iloc[:-1], 
                 df[srs].iloc[-1].to_frame().T])
dft.loc['1989':, srs].to_csv(data_dir / 'unemp2.csv', index_label='date', 
            float_format='%g')

srs = ['White', 'Black', 'Hispanic']
df.loc['1989':, srs].to_csv(data_dir / 'unemp.csv', index_label='date', 
            float_format='%g')

s = series_info(df['Level'])
s2 = series_info(df['Total'])
s3 = series_info(df['Black'])
s4 = series_info(df['U6'])
compare = compare_text(df['Total'].iloc[-1], df['Total'].iloc[-2], [0.15, 1.5, 3.0])
compare2 = compare_text(df['Total'].iloc[-1], df['Total'].iloc[-13], [0.15, 1.5, 3.0])
pryrdt = dtxt(df.index[-13])['mon1']

if compare[-5:] != compare2[-5:]:
    conj = f', but {compare2} the {pryrdt} rate of {df["Total"].iloc[-13]:.1f} percent'
elif compare != compare2:
    conj = f', and {compare2} the {pryrdt} rate of {df["Total"].iloc[-13]:.1f} percent'
else:
    conj = ''
    
text = ('BLS \\href{https://www.bls.gov/news.release/empsit.nr0.htm}{report} '+
        f'{s["val_latest"]/1000:.1f} million '+
        f'unemployed people in {s["date_latest_ft"]}, '+
        f'and an unemployment rate of {s2["val_latest"]} percent '+
        '(see {\\color{violet!70!magenta}\\textbf{---}}), '+
        f'{compare} the {s["date_prev_ft"]} rate of {s2["val_prev"]} percent'+
        f'{conj}.')
write_txt(text_dir / 'unemp1.txt', text)
print(text, '\n')

mval = f', {s4["last_matched"]}.' if s4['days_since_match'] > 500 else '.'
cl = c_line('blue!80!black', dashed=True)
text = (f'In {s["date_latest_ft"]}, U6 is '+
        f'{s4["val_latest"]} percent {cl}{mval}')
write_txt(text_dir / 'unemp2.txt', text)
print(text, '\n')

write_txt(text_dir / 'u6_node.txt', 
          end_node(df['U6'], 'blue!80!black', date='m', offset=0.35))
write_txt(text_dir / 'u3_node.txt', end_node(df['Total'], 'violet!70!magenta'))

black_ch = df['Black'].iloc[-1] - df.loc['2020-02-01', 'Black']
bch = value_text(black_ch, style='above_below', ptype='pp', threshold=0.1)
text = ('Periods of unemployment are more common for disadvantaged groups. '+
        'The black or African American unemployment rate is typically '+
        'double the white unemployment rate. Employment opportunities for '+
        'disadvantaged groups depend more on current labor market '+
        'conditions. Tight labor markets reduce racial '+
        'discrimination in hiring, while disadvantaged groups are more '+
        'likely to lose jobs in downturns. The black unemployment '+
        f'rate is {s3["val_latest"]:.1f} percent, '
        f'{bch} the February 2020 rate '+
        '(see {\\color{green!50!teal!60!black}\\textbf{---}}).')
write_txt(text_dir / 'unemp3.txt', text)
print(text)

BLS \href{https://www.bls.gov/news.release/empsit.nr0.htm}{report} 7.5 million unemployed people in December 2025, and an unemployment rate of 4.4 percent (see {\color{violet!70!magenta}\textbf{---}}), in line with the November 2025 rate of 4.5 percent, but slightly above the December 2024 rate of 4.1 percent.

In December 2025, U6 is 8.4 percent (see {\colordashline{blue!80!black}}).

Periods of unemployment are more common for disadvantaged groups. The black or African American unemployment rate is typically double the white unemployment rate. Employment opportunities for disadvantaged groups depend more on current labor market conditions. Tight labor markets reduce racial discrimination in hiring, while disadvantaged groups are more likely to lose jobs in downturns. The black unemployment rate is 7.5 percent, 1.4 percentage points above the February 2020 rate (see {\color{green!50!teal!60!black}\textbf{---}}).

In [29]:
srs = ['U6', 'Total', 'U1', 'White', 'Black', 'Hispanic', 'Asian']
untab = df[srs].iloc[[-1, -2, -4, -13, -25, -37]].T
untab.columns = untab.columns.strftime('%b `%y')
untab['Peak rate'] = df.loc['2005':'2013', srs].max()
untab['Peak month'] = df.loc['2005':'2013', srs].idxmax().dt.strftime('%b `%y')
d = {'Total': 'Unemployment Rate (U3)',
     'U1': 'Unemployed 15+ Weeks (U1)',
     'U6': 'Under-utilization Rate (U6)',
     'White': '\\hspace{2mm} White',
     'Black': '\\hspace{2mm} Black or African American',
     'Hispanic': '\\hspace{2mm} Hispanic or Latino',
     'Asian': '\\hspace{2mm} Asian'}
untab.index = untab.index.map(d)

untab = untab.astype('str')
untab.loc['\\textit{by race/ethnicity:}', untab.columns] = [''] * 8
untab = pd.concat([untab.iloc[0:3], untab.iloc[-1].to_frame().T, untab.iloc[3:7]])
untab.columns.name = None
write_tbl(data_dir / 'unemp1.tex', untab)
#untab.to_csv(data_dir / 'unemp1.tex', sep='&', lineterminator='\\\\ ', quotechar=' ')

untab

,Dec `25,Nov `25,Sep `25,Dec `24,Dec `23,Dec `22,Peak rate,Peak month
Under-utilization Rate (U6),8.4,8.7,8.1,7.6,7.2,6.6,17.2,Dec `09
Unemployment Rate (U3),4.4,4.5,4.4,4.1,3.8,3.5,10.0,Oct `09
Unemployed 15+ Weeks (U1),1.8,1.8,1.8,1.6,1.4,1.1,5.9,Mar `10
\textit{by race/ethnicity:},,,,,,,,
\hspace{2mm} White,3.8,3.9,3.7,3.6,3.5,3.1,9.2,Oct `09
\hspace{2mm} Black or African American,7.5,8.2,7.6,6.1,5.2,5.8,16.8,Mar `10
\hspace{2mm} Hispanic or Latino,4.9,5.0,5.5,5.1,5.0,4.2,13.0,Aug `09
\hspace{2mm} Asian,3.6,3.6,4.3,3.5,3.1,2.5,8.4,Dec `09

### Labor Force Participation Rate

In [30]:
df = (pd.read_csv(data_dir / 'jobs_report_main2.csv', parse_dates=['date'])
        .set_index('date'))[['MenLFPR', 'WomenLFPR']]
df['TotLFPR'] = (pd.read_csv(data_dir / 'jobs_report_main.csv', 
                             parse_dates=['date'])
                   .assign(TotLFPR = lambda x: (x.LF / x.POP)*100)
                   .set_index('date'))['TotLFPR']
df.loc['1989':].to_csv(data_dir / 'lfpr.csv', index_label='date', 
            float_format='%g')
dfq = pd.concat([df.resample('QS').mean().iloc[:-1], df.iloc[-1].to_frame().T])
dfq.loc['1989':].to_csv(data_dir / 'lfprq.csv', index_label='date', 
            float_format='%g')

col = {'MenLFPR': 'blue!70!black',
       'WomenLFPR': 'red!80!black',
       'TotLFPR': 'green!80!blue!60!black'}
nodes = (end_node(df['MenLFPR'], col['MenLFPR'], date='m', 
                  offset=0.35) + '\n' + 
         '\n'.join(end_node(df[name], color) 
                   for name, color in col.items() if name != 'MenLFPR'))
write_txt(text_dir / 'lfpr_nodes.txt', nodes)

tot = df['TotLFPR']
ltdt = dtxt(df.index[-1])['mon1']
write_txt(text_dir / 'lfpr_blsdate.txt', ltdt)
prdt, prdt2 = (dtxt(df.index[i])['mon3'] 
               if df.index[-1].year == df.index[i].year 
               else dtxt(df.index[i])['mon1'] 
               for i in [-2, -3])
cpdt = '2020-02-01'
compdt = dtxt(cpdt)['mon1']
feb20val = tot.loc[cpdt]
mltval = df['MenLFPR'].iloc[-1]
wltval = df['WomenLFPR'].iloc[-1]
mchval = mltval - df['MenLFPR'].loc['2020-01-01']
wchval = wltval - df['WomenLFPR'].loc['2020-01-01']
mch = value_text(mchval, style='increase', ptype='pp')
wch = value_text(wchval, style='increase', ptype='pp')
cl = {k: c_line(v) for k, v in col.items()}
v1, v2, v3 = [value_text(tot.iloc[i], 'plain') for i in [-1, -2, -3]]
chtxt = 'following'
comptxt = (f', {chtxt} {v2} in {prdt} and {v3} in {prdt2}')
if v1 == v2 == v3:
    comptxt = (f', the same as in {prdt} and {prdt2}')
elif v1 != v2 != v3:
    comptxt = comptxt
else:
    print('Partial match \n')
    if v1 == v2:
        comptxt = (f', unchanged from {prdt}, and following {v3} in {prdt2}')
    if v1 == v3:
        comptxt = comptxt
    if v2 == v3:
        comptxt = (f', {chtxt} {v2} in both {prdt} and {prdt2}')

est24 = 60.9
val24 = df.loc['2024', 'TotLFPR'].mean()
diff24 = val24 - est24
text = (f'As of {ltdt}, {v1} of those aged 16 and over are '+
        f'in the labor force {cl["TotLFPR"]}{comptxt}. The 2024 average '+
        f'participation rate of {val24:.1f} percent is {diff24:.1f} percentage '+
        'points above the December 2015 forecast. Pre-pandemic, '+
        f'in {compdt}, the rate stood at {feb20val:.1f} percent.\n\n'+
        f'In {ltdt}, {mltval:.1f} percent of men age '+
        f'16 and older are in the labor force {cl["MenLFPR"]}, compared to '+
        f'{wltval:.1f} percent of women {cl["WomenLFPR"]}. Since '+
        f'{compdt}, participation has {mch} among men, '+
        f'and {wch} among women.')
write_txt(text_dir / 'lfpr_text.txt', text)
print(text)

Partial match

As of December 2025, 62.4 percent of those aged 16 and over are in the labor force (see {\color{green!80!blue!60!black}\textbf{---}}), following 62.5 percent in both November and October. The 2024 average participation rate of 62.6 percent is 1.7 percentage points above the December 2015 forecast. Pre-pandemic, in February 2020, the rate stood at 63.3 percent.

In December 2025, 67.7 percent of men age 16 and older are in the labor force (see {\color{blue!70!black}\textbf{---}}), compared to 57.3 percent of women (see {\color{red!80!black}\textbf{---}}). Since February 2020, participation has decreased 1.5 percentage points among men, and decreased 0.5 percentage point among women.

### Employment rate

In [2]:
url = 'https://data.bls.gov/timeseries/LNS12300000'
pa_url = 'https://data.bls.gov/timeseries/LNS12300060'
df1 = (pd.read_csv(data_dir / 'jobs_report_main.csv', 
                  index_col='date', parse_dates=True)
        .loc['1989':, 'PA_EPOP'])
df2 = (pd.read_csv(data_dir / 'jobs_report_main2.csv', 
                  index_col='date', parse_dates=True)
        .loc['1989':, 'EPOP'])
df = pd.concat([df1, df2], axis=1)
df.to_csv(data_dir / 'epop.csv', index_label='date', 
            float_format='%g')

color = 'green!60!black'
node = end_node(df['EPOP'], color, date='m')
write_txt(text_dir / 'epop_node2.txt', node)

ltdt = dtxt(df.index[-1])['mon1']
ltval = df['EPOP'].iloc[-1]
chval = df['EPOP'].diff(12).iloc[-1]
chtxt = value_text(chval, 'increase_of', ptype='pp', time_str='one-year ')
chval2 = df['EPOP'].iloc[-1] - df.loc['2019', 'EPOP'].mean()
chtxt2 = value_text(chval2, style='increase_end', ptype='pp')
ab = 'but'
if ((chval<0) == (chval2<0)) == True:
    ab = 'and'
text = (f'As of {ltdt}, the Bureau of Labor Statistics '+
        f'\\href{{{url}}}{{report}} '+
        f'an overall (age 16 and older) employment rate of {ltval} '+
        f'percent {c_line(color)}, {chtxt}, {ab} {chtxt2} since 2019.')
write_txt(text_dir / 'epop_text2.txt', text)
print(text)

color = 'blue!90!cyan'
adj = 0
if (df['PA_EPOP'].iloc[-1] / df['PA_EPOP'].max()) > 0.95:
    adj = -0.25
elif (df['PA_EPOP'].iloc[-1] / df['PA_EPOP'].max()) > 1:
    adj = -0.4
node = end_node(df['PA_EPOP'], color, date='m', offset=adj)
write_txt(text_dir / 'epop_node.txt', node)

ltval = df['PA_EPOP'].iloc[-1]
prval = df['PA_EPOP'].iloc[-2]
prdt = dtxt(df['PA_EPOP'].index[-2])['mon1']
prtxt = f'compared to {prval} percent in {prdt}'
compval = df['PA_EPOP'].loc['2019-06-01': '2020-03-01'].max()
last = series_info(df['PA_EPOP'])['last_matched']
text2 = prtxt if ltval < compval else last
chtxt = value_text(df['PA_EPOP'].diff(12).iloc[-1], ptype='pp', threshold=0.1)

pop = (cps_1mo(cps_dir, cps_date(), ['BASICWGT', 'AGE'])
       .query('25 <= AGE <=54').BASICWGT.sum()) / 1_000
rt99 = df['PA_EPOP'].loc['1999': '2000'].mean()
ch99 =  ltval - rt99
ch99w = (-ch99 / 100) * pop
ch99t = (f'{round(abs(ch99w) / 1000, 1)} million' 
         if ch99w > 999 else f'{round(abs(ch99w), -1):.0f},000')
ch99t2 = f'(equivalent to {ch99t} workers)'
threshold = 0.1
txt = value_text(ch99, style='above_below', 
                 ptype='pp', threshold=threshold)
if abs(ch99) > threshold:
    ch99txt = f'{txt[:-6]} {ch99t2} {txt[-5:]}'
else:
    ch99txt = txt
text = (f'In {ltdt}, {ltval} percent of 25 to 54 year-olds were '+
        f'employed {c_line(color)}, {text2}. Over the past year, '+
        f'the age 25 to 54 employment rate {chtxt}. The {ltdt} rate '+
        f'is {ch99txt} the average rate of {rt99:.1f} during the '+
        'tight labor market of 1999--2000.')
write_txt(text_dir / 'epop_text.txt', text)
print(text)

As of December 2025, the Bureau of Labor Statistics \href{https://data.bls.gov/timeseries/LNS12300000}{report} an overall (age 16 and older) employment rate of 59.7 percent (see {\color{green!60!black}\textbf{---}}), a one-year decrease of 0.2 percentage point, and a 1.1 percentage point decrease since 2019.
In December 2025, 80.7 percent of 25- to 54-year-olds were employed (see {\color{blue!90!cyan}\textbf{---}}), the highest level since September 2025. Over the past year, the age 25 to 54 employment rate increased 0.2 percentage point. The December 2025 rate is 0.7 percentage point (equivalent to 970,000 workers) below the average rate of 81.4 during the tight labor market of 1999--2000.

### Recent Values

In [3]:
df1 = (pd.read_csv(data_dir / 'jobs_report_main.csv', 
                  index_col='date', parse_dates=True)
        .loc['1989':, 'PA_EPOP'])
df2 = (pd.read_csv(data_dir / 'jobs_report_main2.csv', 
                  index_col='date', parse_dates=True)
        .loc['1989':, ['PA_EPOP_M', 'PA_EPOP_W']])
df = pd.concat([df1, df2], axis=1)
df['label'] = [dt.strftime('%b\\\\%Y') if dt.month == 1 
                  else dt.strftime('%b') if dt.month == 7
                  else '' for dt in df.index]
res = df.iloc[-25:]

res.to_csv(data_dir / 'pa_epop_rec.csv', index_label='date')

In [4]:
sdt = res.index[0]
sdtime = (dtxt(sdt)['datetime']
           .replace('-08-', '-8-').replace('-09-', '-9-'))
ltdt = res.index[-1]
ltdtime = (dtxt(ltdt)['datetime']
           .replace('-08-', '-8-').replace('-09-', '-9-'))
node = []
d = {'PA_EPOP': ['blue!80!purple', 'blue!80!purple'], 
     'PA_EPOP_M': ['green!50!black', 'green!50!black'], 
     'PA_EPOP_W': ['green!80!yellow!80!black', 'green!80!yellow!80!black']}
for s, [c1, c2] in d.items():
    dt = f'\\scriptsize {dtxt(ltdt)["mon6"]} \\\\' if s == 'PA_EPOP_M' else ''
    v0 = res[s].iloc[0]
    vlt = res[s].iloc[-1]
    y = 0.15 if s == 'PA_EPOP_M' else '0'
    x = -0.3 if s == 'PA_EPOP_M' else '-0.05'
    n0 = ('\\node[label={[yshift=0cm, xshift=0.05cm, align=right]180:'+
          f'{{\\scriptsize {v0:.1f}}}}}, circle, draw={c1}, fill={c2}, '+
          f'inner sep=1pt] at (axis cs:{sdtime}, {v0}) '+
          '{};\n'+
          f'\\node[label={{[yshift={y}cm, xshift={x}cm, align=right]0:'+
          f'{{{dt}\\scriptsize {vlt:.1f}}}}}, circle, draw={c1}, fill={c2}, '+
          f'inner sep=1pt] at (axis cs:{ltdtime}, {vlt}) '+
          '{};')
    node.append(n0)
    
# Text labels
k = [['south east', 'right', dtxt(res.index[10])['datetime2'], 
  res['PA_EPOP_M'].iloc[10], 'green!50!black', '\\footnotesize Men'], 
 ['north west', 'left', dtxt(res.index[4])['datetime2'], 
  res['PA_EPOP_W'].iloc[4], 'green!80!yellow!80!black', '\\footnotesize Women'], 
 ['south east', 'left', dtxt(res.index[15])['datetime2'], 
  res['PA_EPOP'].iloc[15], 'blue!80!purple', '\\small Total']]

tnode = [(f'\\node[anchor={anchor}, align={align}] at '+
         f'({{{dt}}}, {val}) {{\\color{{{color}}}{name}}};') 
         for anchor, align, dt, val, color, name in k]

nodes = '\n'.join([n for n in [*node, *tnode]])
write_txt(text_dir / 'epop_summary_nodes.txt', nodes)

In [5]:
df.iloc[[-25, -13, -3, -2, -1]].T.iloc[:, ::-1]

date      2025-12-01 2025-11-01 2025-10-01 2024-12-01 2023-12-01
PA_EPOP         80.7       80.6      80.65       80.5       80.5
PA_EPOP_M       86.4       86.2      86.25       86.0       86.2
PA_EPOP_W       75.1       75.1       75.1       75.1       74.8
label

### Unemployment by reason

In [6]:
srs = ['Job Loser', 'Job Leaver', 'Re-entrant', 'New entrant', 
       'Temporary Layoff', 'Permanent Separation', 'Level']
d1 = (pd.read_csv(data_dir / 'jobs_report_main.csv', 
                  parse_dates=['date'])
        .set_index('date')).loc['1989':]

df = d1[srs].div(d1['LF'], axis='index') * 100
dfa = df.resample('YS').mean()
dfa.index = dfa.index + pd.DateOffset(months=6)
dfa.to_csv(data_dir / 'unemp_reason.csv', index_label='date', 
          float_format='%g')

lt = df.iloc[-3:]
lt.index = [dtxt(i)['mon7'] for i in lt.index]
lt = pd.concat([df.rolling(12).mean().iloc[-1].rename('12m avg'), lt.T], axis=1).T
lt.to_csv(data_dir / 'unemp_reason_mon.csv', index_label='date', 
          float_format='%g')

x_val = dtxt(dfa.index[-1])['datetime']
x_valpr = dtxt(dfa.index[-2])['datetime']
y_val = dfa.Level.iloc[-1]
prelim = '(p)' if df.index[-1].month != 12 else ''
yrp = f'{dtxt(dfa.index[-1])["year"][2:]}{prelim}'
barh = ('\\addplot[ybar, bar width=5.4pt, draw=black, fill=white!0] '+
        f'plot coordinates{{({x_val},{y_val})}};\n'+
        f'\\absnode{{{x_valpr}}}{{-0.25}}{{\\scriptsize \\color{{black!70}} {yrp}}};')
write_txt(text_dir / 'unemp_rsn_ltbar.txt', barh)

cols = ['Job Loser', 'New entrant', 'Re-entrant', 'Job Leaver']
sdf = lt[cols].iloc[-1]
height = ((sdf.cumsum() - (sdf / 2) + 0.25)).to_dict()
val = sdf.to_dict()
nodes = [f'\\absnode{{3.3}}{{{height[i]}}}{{\\scriptsize {val[i]:.1f}}}' for i in cols]
nodetext = '\n'.join(nodes)
write_txt(text_dir / 'unemp_rsn_ltval.txt', nodetext)

colors = {'Job Loser': 'red!75!orange!70!white', 'New entrant': 'purple!80!red!85!black', 
          'Re-entrant': 'blue!70!teal!70!gray!62!white', 'Job Leaver': 'blue!72!black'}
cl = {k: c_box(v) for k, v in colors.items()}

ltdt = dtxt(df.index[-1])['mon1']
lt = df.iloc[-1]
jlsh = lt['Job Loser']
jl = (d1['Job Loser'].iloc[-1] / 1_000)
jle = lt['Job Leaver']
re = lt['Re-entrant']
ne = lt['New entrant']
text = ('There are several \\textbf{reasons for unemployment}. In '+
        f'{ltdt}, {jl:.1f} million people, or {jlsh:.1f} percent of '+
        'the labor force, were unemployed from losing their job '+
        f'{cl["Job Loser"]}. An additional {jle:.1f} percent '+
        f'voluntarily left a job {cl["Job Leaver"]}. Re-entrants, '+
        'people who left the labor force but are looking for a new '+
        f'job, comprised {re:.1f} percent {cl["Re-entrant"]}. Lastly, '+
        f'{ne:.1f} percent of the labor force were new entrants to '+
        f'the labor market, looking for their first job '+
        f'{cl["New entrant"]}.')
write_txt(text_dir / 'unemp_rsn.txt', text)
print(text)

lf = ['Employed', 'Unemployed']
naw_rate = lambda x: np.average(x['NOTATWORK'], weights=x['BASICWGT'])

columns = ['LFS', 'MONTH', 'YEAR', 'BASICWGT', 'NOTATWORK']

naw = (pd.concat([(pd.read_feather(cps_dir / f'cps{year}.ft', columns=columns)
              .query('LFS in @lf'))
           for year in range(2009, 2026)])
        .groupby(['YEAR', 'MONTH'])
        .apply(naw_rate, include_groups=False) * 100)
naw.index = [pd.to_datetime(f'{ti[0]}-{ti[1]}-01') for ti in naw.index]
df['Employed, Not at Work'] = naw

tbl = df.iloc[[-25, -13, -3, -2, -1]].T.iloc[:, ::-1]
tbl.columns = [dtxt(i)['mon6'] for i in tbl.columns]
#tbl['12m Avg.'] = df.rolling(12).mean().iloc[-1]
tbl['Apr `20'] = df.loc['2020-04-01']
tbl['2017 --`19'] = df.loc['2017': '2019'].mean()
tbl['2009 --`11'] = df.loc['2009': '2011'].mean()
tbl = tbl.round(1)
d = {'Level': '\\ Unemployed, Any Reason',
     'Job Loser': f'\\hspace{{1mm}}\\cbox{{{colors["Job Loser"]}}} Job Loser',
     'Temporary Layoff': '\\hspace{4mm}Temporary Layoff',
     'Permanent Separation': '\\hspace{4mm}Permanent Separation',
     'Re-entrant': f'\\hspace{{1mm}}\\cbox{{{colors["Re-entrant"]}}} Re-entrant',
     'New entrant': f'\\hspace{{1mm}}\\cbox{{{colors["New entrant"]}}} New entrant',
     'Job Leaver': f'\\hspace{{1mm}}\\cbox{{{colors["Job Leaver"]}}} Job Leaver'}

final = tbl.loc[d.keys()].rename(d).astype('str')

final.loc['\\textit{See also:}', final.columns] = [''] * 8
final.loc['\\ \\ Employed, Not at Work*'] = tbl.loc['Employed, Not at Work']
write_tbl(data_dir / 'unempreason_table.tex', final)

tl = lt['Temporary Layoff']
pjl = lt['Permanent Separation']

text = (f'In {ltdt}, temporary layoffs were {tl:.1f} percent of '+
        f'the labor force. Permanent job losses were {pjl:.1f} '+
        'percent of labor force. ')
write_txt(text_dir / 'unemp_rsn2.txt', text)
print('\n', text)

There are several \textbf{reasons for unemployment}. In December 2025, 3.5 million people, or 2.0 percent of the labor force, were unemployed from losing their job \seebox{red!75!orange!70!white}. An additional 0.5 percent voluntarily left a job \seebox{blue!72!black}. Re-entrants, people who left the labor force but are looking for a new job, comprised 1.4 percent \seebox{blue!70!teal!70!gray!62!white}. Lastly, 0.5 percent of the labor force were new entrants to the labor market, looking for their first job \seebox{purple!80!red!85!black}.

 In December 2025, temporary layoffs were 0.5 percent of the labor force. Permanent job losses were 1.1 percent of labor force.

### Unemployed long-term

In [7]:
srs = ['LT', 'MT', 'POP', 'LF']
df = (pd.read_csv(data_dir / 'jobs_report_main.csv', parse_dates=['date'])
        .set_index('date')).loc['1989':, srs]

data = (df.divide(df['LF'], axis=0) * 100).drop(['POP'], axis=1)
data.to_csv(data_dir / 'ltu.csv', index_label='date', float_format='%g')

collt = 'blue'
node = end_node(data['LT'], collt, date='m', digits=2, offset=0.35)
write_txt(text_dir / 'ltu_node.txt', node)
colmt = 'violet!90!black'
node = end_node(data['MT'], colmt, digits=2, date='m', offset=0.35)
write_txt(text_dir / 'ltu_node2.txt', node)

dates = date_list(data)
pydt = dtxt(data.index[-13])['mon1']
mxdt = dtxt(data['LT'].idxmax())['mon1']
vl1 = value_text(data["LT"].iloc[-1], 'plain', digits=2)
v1 = value_text(data["MT"].iloc[-1], 'plain', digits=2)
v2 = value_text(data["MT"].iloc[-2], 'plain', digits=2)
v3 = value_text(data["MT"].iloc[-3], 'plain', digits=2)
comptxt = (f'{v1} in {dates[1]} and {v2} in {dates[2]}.')
if v2 == v3:
    comptxt = (f'{v2} in both {dates[1]} and {dates[2]}')
mtv = value_text(df['MT'].iloc[-1] / 1000, 'plain', 'million')

cllt = c_line(collt)
clmt = c_line(colmt)
recent_min = data.loc['2015':'2020-02-01', 'LT'].min()
recent_min_dt = dtxt(data.loc['2015':'2020-02-01', 'LT'].idxmin())['mon1']
url = 'https://www.bls.gov/webapps/legacy/cpsatab12.htm'
text = (f'As of {dates[0]}, BLS \\href{{{url}}}{{reports}} that '+
        f'{vl1} of the labor force have been '+
         'unemployed for 27 weeks or longer, compared to '+
        f'{data["LT"].iloc[-13]:.2f} percent in {pydt} {cllt}. '+
        'This measure of \\textbf{long-term unemployment} peaked '+
        f'at {data["LT"].max():.2f} percent of the labor force '+
        f'in {mxdt}, but had fallen to {recent_min:.2f} percent '+
        f'in {recent_min_dt}.\n\n In {dates[0]}, {mtv} people, '+
        f'equivalent to {v1} of the labor force, '+
        'have been unemployed for at least 15 '+
        f'weeks {clmt}, following {comptxt}. One year prior, in '+
        f'{pydt}, {data["MT"].iloc[-13]:.2f} percent are unemployed '+
        'for 15 weeks or more. ')
write_txt(text_dir / 'ltu.txt', text)
print(text)

As of December 2025, BLS \href{https://www.bls.gov/webapps/legacy/cpsatab12.htm}{reports} that 1.08 percent of the labor force have been unemployed for 27 weeks or longer, compared to 0.87 percent in December 2024 (see {\color{blue}\textbf{---}}). This measure of \textbf{long-term unemployment} peaked at 4.54 percent of the labor force in April 2010, but had fallen to 0.67 percent in December 2019.

 In December 2025, three million people, equivalent to 1.74 percent of the labor force, have been unemployed for at least 15 weeks (see {\color{violet!90!black}\textbf{---}}), following 1.74 percent in both November and October. One year prior, in December 2024, 1.54 percent are unemployed for 15 weeks or more.

### Duration of Unemployment

In [8]:
s = {'Median': 'green!75!blue', 'Mean': 'blue!60!cyan'}
df = (pd.read_csv(data_dir / 'jobs_report_main.csv', 
                  parse_dates=['date'])
        .set_index('date')).loc['1989':, s.keys()]
df.to_csv(data_dir / 'unempdur.csv', index_label='date', 
          float_format='%g')
ltdt = dtxt(df.index[-1])['mon1']
lt = df.iloc[-1]

adj = node_adj(df)
smax = df.iloc[-1].idxmax()
adj[smax] = adj[smax] + 0.35

date = {series: 'm' if series == smax else None 
        for series in s.keys()}
nodes  ='\n'.join([end_node(df[series], color, 
                            date=date[series], 
                            size=1.1, offset=adj[series]) 
                   for series, color in s.items()])
write_txt(text_dir / 'unempdur_nodes.txt', nodes) 

pc_yr = df.loc['2019-03-01':'2020-02-01'].mean()
text = (f'Among those who are unemployed in {ltdt}, the average '+
        f'(mean) \\textbf{{duration of unemployment}} is {lt.Mean:.1f} '+
        f'weeks {c_line(s["Mean"])}, and the typical (median) '+
        f'duration of unemployment is {lt.Median:.1f} weeks '+
        f'{c_line(s["Median"])}. Over the year '+
        'prior to COVID-19, ending February 2020, the '+
        'average duration of unemployment was '+
        f'{pc_yr.Mean:.1f} weeks and the typical '+
        f'duration was {pc_yr.Median:.1f} weeks.')
write_txt(text_dir / 'unempdur.txt', text)
print(text)

Among those who are unemployed in December 2025, the average (mean) \textbf{duration of unemployment} is 24.4 weeks (see {\color{blue!60!cyan}\textbf{---}}), and the typical (median) duration of unemployment is 11.4 weeks (see {\color{green!75!blue}\textbf{---}}). Over the year prior to COVID-19, ending February 2020, the average duration of unemployment was 21.7 weeks and the typical duration was 9.2 weeks.

### Part-Time Workers

In [9]:
srs = ['PTECON', 'PTNONECON', 'LF']
df = (pd.read_csv(data_dir / 'jobs_report_main.csv', 
                  index_col='date', parse_dates=True)
        .loc['1989':, srs])
df['TOTAL'] = df['PTECON'] + df['PTNONECON']
# Total part-time for summary text
text = (f'Around {df.TOTAL.iloc[-1] / 1000:.0f} million people '+
        'work part-time, defined as fewer than 35 hours per week, '+
        'and the reasons for doing so vary.')
write_txt(text_dir / 'pt_tot.txt', text)
print(text, '\n')

# Share of labor force
data = (df.divide(df.LF, axis=0) * 100)
data = data.loc['1994':, ['PTECON', 'PTNONECON', 'TOTAL']]
data.to_csv(data_dir / 'parttime.csv', index_label='date', 
            float_format='%g')

dq = pd.concat([data.resample('QS').mean().iloc[:-1], 
                data.iloc[-1].to_frame().T])
dq.to_csv(data_dir / 'parttimeq.csv', index_label='date', 
            float_format='%g')

color = 'red'
col2 = 'orange!80!yellow'
node = end_node(data.PTECON, color)
node2 = end_node(data.PTNONECON, col2, 
                 date='m', offset=-0.3)
nodes = node + '\n' + node2
write_txt(text_dir / 'pt_nodes.txt', nodes)

ltdt = dtxt(df.index[-1])['mon1']
lttot = df.PTECON.iloc[-1] / 1_000
ltvpt = df.PTNONECON.iloc[-1] / 1_000
ltsh = data.PTECON.iloc[-1]
val19 = data.loc['2019', 'PTECON'].mean()
val10 = data.loc['2010', 'PTECON'].mean()
ltvsh = value_text(data.PTNONECON.iloc[-1], 'plain')
vsh19 = value_text(data.loc['2019', 'PTNONECON'].mean(), 'plain')
also = 'also ' if ltvsh == vsh19 else ''

text = (f'In {ltdt}, {lttot:.1f} million people worked part-time '+
        f'for economic reasons, equivalent to {ltsh:.1f} percent '+
        f'of the labor force {c_line(color)}. In 2019, an average '+
        f'of {val19:.1f} percent of the labor force worked part-time '+
        'for economic reasons. In 2010, following the Great '+
        f'Recession, the rate was {val10:.1f} percent.\n\nVoluntary '+
        f'part-time workers total {ltvpt:.1f} million in {ltdt}, or '+
        f'{ltvsh} of the labor force {c_line(col2)}. The '+
        f'category is {also}{vsh19} of the labor force in '+
        '2019, on average.')
write_txt(text_dir / 'parttime.txt', text)
print(text)

Around 28 million people work part-time, defined as fewer than 35 hours per week, and the reasons for doing so vary.

In December 2025, 5.3 million people worked part-time for economic reasons, equivalent to 3.1 percent of the labor force (see {\color{red}\textbf{---}}). In 2019, an average of 2.7 percent of the labor force worked part-time for economic reasons. In 2010, following the Great Recession, the rate was 5.8 percent.

Voluntary part-time workers total 22.3 million in December 2025, or 13.0 percent of the labor force (see {\color{orange!80!yellow}\textbf{---}}). The category is 13.1 percent of the labor force in 2019, on average.

### Multiple Jobholders

In [10]:
df = (pd.read_csv(data_dir / 'jobs_report_main2.csv', 
                  index_col='date', parse_dates=True)
        .loc['1989':, ['MJHsa', 'EMPsa']])
data = ((df.MJHsa / df.EMPsa) * 100).dropna().rename('MJH')
d3m = data.rolling(3).mean()
d3m.to_csv(data_dir / 'mjh.csv', index_label='date', 
            float_format='%g')
dq = (pd.concat([data.resample('QS').mean().iloc[:-1], 
                 pd.Series({d3m.index[-1]: d3m.iloc[-1]})])
     ).round(2).rename('MJH')
dq.to_csv(data_dir / 'mjhq.csv', index_label='date', 
            float_format='%g')
color = 'blue!50!violet!80!black'
node = end_node(d3m, color, size=1.2, date='m')
write_txt(text_dir / 'mjh_node.txt', node)

ltdt = dtxt(df.index[-1])['mon1']
totval = df.MJHsa.iloc[-1] / 1_000
ltval = value_text(data.iloc[-1], 'plain')
l3val = f'{d3m.iloc[-1]:.1f}'
l19val = data.loc['2019'].mean()
comp_date = '2020-02-01'
same = 'Over' # Less awkward text when latest and 3ma match
if ltval == l3val:
    same = 'Likewise, over'

text = (f'In {ltdt}, a seasonally-adjusted total of {totval:.1f} '+
        'million people \\textbf{worked '+
        'more than one job} during the survey reference week, '+
        f'equivalent to {ltval} of workers. '+
        f'{same} the three months ending {ltdt}, an average of '+
        f'{l3val} percent of workers were multiple '
        f'jobholders {c_line(color)}. In 2019, an average of '+
        f'{l19val:.1f} percent of workers had more than one job '+
        'during the survey reference week. ')
write_txt(text_dir / 'mjh.txt', text)
print(text)

In December 2025, a seasonally-adjusted total of 8.8 million people \textbf{worked more than one job} during the survey reference week, equivalent to 5.4 percent of workers. Over the three months ending December 2025, an average of 5.5 percent of workers were multiple jobholders (see {\color{blue!50!violet!80!black}\textbf{---}}). In 2019, an average of 5.1 percent of workers had more than one job during the survey reference week.

### Self-Employed

In [11]:
df = (pd.read_csv(data_dir / 'jobs_report_main2.csv', 
                  index_col='date', parse_dates=True)
        .loc['1988':, ['seinc', 'seuninc', 'LFnsa']])

df2 = (pd.read_csv(data_dir / 'jobs_report_main.csv', 
                  index_col='date', parse_dates=True)
        .loc['1988':, ['LF']])

df3 = pd.read_csv(data_dir / 'se_inc_hist.csv', index_col='date', 
                  parse_dates=True)

uninc = (df['seuninc'].divide(df2['LF'], axis=0) * 100).rename('uninc')
inc = (df['seinc'].divide(df['LFnsa'], axis=0) * 100).rename('inc')
INC = (df3.INC.divide(df['LFnsa'], axis=0) / 10).rename('INC')
res = uninc.to_frame().join(inc).join(INC).loc['1989':]
res.to_csv(data_dir / 'selfemp.csv', index_label='date', 
            float_format='%g')
resq = (pd.concat([res.resample('QS').mean().iloc[:-1], 
                   res.iloc[-1].to_frame().T])).round(1)
resq.to_csv(data_dir / 'selfempq.csv', index_label='date', 
            float_format='%g')

dft = res[['inc', 'uninc']]

adj = node_adj(dft)
smax = dft.iloc[-1].idxmax()
adj[smax] = adj[smax] + 0.35

colors = {'inc': 'green!80!black', 
          'uninc': 'purple'}
date = {series: 'm' if series == smax else None 
        for series in colors.keys()}
nodes  ='\n'.join([end_node(dft[series], color, 
                            date=date[series], 
                            size=1.1, offset=adj[series]) 
                   for series, color in colors.items()])
write_txt(text_dir / 'selfemp_nodes.txt', nodes)

In [12]:
ltdt = dtxt(res.index[-1])['mon1']
seutot = df['seuninc'].iloc[-1] / 1_000
seush = res['uninc'].iloc[-1]
seu1yr = res['uninc'].iloc[-12:].mean()
seu19 = res.loc['2019', 'uninc'].mean()
seu89 = value_text(res.loc['1989':'1994', 'uninc'].mean(), 'plain')

text = (f'As of {ltdt}, there are {seutot:.1f} million \\textbf{{unincorporated '+
        f'self-employed}}, equivalent to {seush:.1f} percent of the labor '+
        f'force {c_line(colors["uninc"])}. Over the past year, the '+
        f'unincorporated self-employed made up an average of {seu1yr:.1f} '+
        f'percent of the labor force, compared to an average of {seu19:.1f} '+
        'percent in 2019. From 1989 to 1994, the category made up an '+
        f'average of {seu89} of the labor force. ')
write_txt(text_dir / 'selfemp1.txt', text)
print(text, '\n')

seitot = df['seinc'].iloc[-1] / 1_000
seish = res['inc'].iloc[-1]
sei19 = res.loc['2019', 'inc'].mean()
sei89 = value_text(res.loc['1989':'1999', 'INC'].mean(), 'plain')

text = (f'The \\textbf{{incorporated self-employed}} total {seitot:.1f} million '+
        f'in {ltdt}, equivalent to {seish:.1f} percent of the labor force '+
        f'{c_line(colors["inc"])}. In 2019, the category made up {sei19:.1f} percent '+
        'of the labor force.\n\nIncorporated self-employed are not reported by '+
        'BLS prior to 2000, but can be calculated from the CPS, and make up an '+
        f'average of {sei89} of the labor force from 1989 to 1999. ')
print(text)
write_txt(text_dir / 'selfemp2.txt', text)

As of December 2025, there are 9.8 million \textbf{unincorporated self-employed}, equivalent to 5.7 percent of the labor force (see {\color{purple}\textbf{---}}). Over the past year, the unincorporated self-employed made up an average of 5.8 percent of the labor force, compared to an average of 5.8 percent in 2019. From 1989 to 1994, the category made up an average of eight percent of the labor force.

The \textbf{incorporated self-employed} total 6.9 million in December 2025, equivalent to 4.1 percent of the labor force (see {\color{green!80!black}\textbf{---}}). In 2019, the category made up 3.8 percent of the labor force.

Incorporated self-employed are not reported by BLS prior to 2000, but can be calculated from the CPS, and make up an average of three percent of the labor force from 1989 to 1999.

### Flows, Newly Employed, Not looking for work previously

In [13]:
df = (pd.read_csv(data_dir / 'jobs_report_main.csv', 
                  parse_dates=['date'])
        .set_index('date')).loc['1990':, ['NILF', 'UNEMP', 'Total']]
df['TOTAL'] = df[['NILF', 'UNEMP']].astype('float').sum(axis=1)
sh = ((df['NILF'] / df['TOTAL']).rename('total') * 100).to_frame()
sh['UNEMP'] = (df['UNEMP'] / df['TOTAL']).rename('UNEMP') * 100

sh.to_csv(data_dir / 'lf_flow.csv', index_label='date', 
          header=True, float_format='%g')
ma = sh.resample('QS').mean()
ma.to_csv(data_dir / 'lf_flow_q.csv', index_label='date', 
          header=True, float_format='%g')

col = 'green!60!teal!80!black'
col2 = 'lime!80!green'
node = end_node(ma['total'], col, date='q', size=1.2)
write_txt(text_dir / 'lf_flow_node.txt', node)

totval = df['TOTAL'].iloc[-1] / 1000
shval = value_text(sh.total.iloc[-1], 'plain', trail_zero=False)
prval = value_text(sh.total.iloc[-13], 'plain', trail_zero=False)
maval = value_text(ma.total.iloc[-1], 'plain')

lowdt = df.Total.idxmin()
lowdate = dtxt(lowdt)['mon1']
lowval = value_text(df.loc[lowdt, 'Total'], 'plain')
shlow = value_text(sh.loc[lowdt, 'total'], 'plain')
ltdt = dtxt(sh.index[-1])['mon1']
prdt = dtxt(sh.index[-13])['mon1']

text = (f'Of those newly employed in {ltdt}, '+
        f'{shval} were out of the labor force '+
        f'the month prior {c_line(col)}, compared to '+
        f'{prval} in {prdt}; '+
        'the rest were previously unemployed.\n\nWhen '+
        'unemployment is low, the newly employed are more '+
        f'likely to come from outside of the labor force. In {lowdate}, '+
        f'when the unemployment rate was {lowval}, {shlow} of '+
        'the newly employed had not looked for work the previous month.')
write_txt(text_dir / 'lf_flow.txt', text)
print(text)

Of those newly employed in December 2025, 72.8 percent were out of the labor force the month prior (see {\color{green!60!teal!80!black}\textbf{---}}), compared to 70.4 percent in December 2024; the rest were previously unemployed.

When unemployment is low, the newly employed are more likely to come from outside of the labor force. In April 2023, when the unemployment rate was 3.4 percent, 74.6 percent of the newly employed had not looked for work the previous month.

### Labor Force Participation Summary Chart

In [14]:
# Retrieve Data
df = pd.concat([pd.read_csv(data_dir / f'jobs_report_{f}.csv', 
                            index_col='date', parse_dates=True) 
                for f in ['main', 'main2']], axis=1)
df['Other_NILF'] = df['NILF_Level'] - df['NILF_WantJob']
col = ['EMPsa', 'Level', 'NILF_WantJob', 'Other_NILF']
rn = {'Level': 'Unemployed', 'EMPsa': 'Employed'}
data = df[col].rename(rn, axis=1).divide(df['POP'], axis=0) * 100

# Latest and previous year
lt = data.iloc[-1]
pr = data.iloc[-13]
ltdt = dtxt(data.index[-1])['mon1']
prdt = dtxt(data.index[-13])['mon1']

# Chart buffers and settings
buffer_e = 50
buffer_n = 28
spl = 0.4
end = 1.4
adj = buffer_e + buffer_n - (2*spl) - (2*end)
tmp = {1: {'Employed1': end, 'Employed2': spl, 'Employed3': lt.Employed - buffer_e, 
           'Unemployed': lt.Unemployed, 'WantJob': lt.NILF_WantJob, 
           'ONILF1': lt.Other_NILF - buffer_n, 
           'ONILF2': spl, 'ONILF3': end},
       0: {'Employed1': end, 'Employed2': spl, 'Employed3': pr.Employed - buffer_e, 
           'Unemployed': pr.Unemployed, 'WantJob': pr.NILF_WantJob, 
           'ONILF1': pr.Other_NILF - buffer_n, 
           'ONILF2': spl, 'ONILF3': end}}
res = pd.DataFrame(tmp).T
res['LFPR'] = res[[i for i in res.columns if 'ploy' in i]].sum(axis=1)
res.to_csv(data_dir / 'lfp_overview.csv', index_label='name', 
          header=True)

# Summary Text
lfn = (df[col].rename(rn, axis=1)[['Employed', 'Unemployed']]
       .sum(axis=1).divide(1000)
       .apply(lambda x: value_text(x, 'plain', 'none', 
                                   trail_zero=False) + ' million'))
ltv = value_text(lt.Employed + lt.Unemployed, 'plain', trail_zero=False)
prv = value_text(pr.Employed + pr.Unemployed, 'plain', trail_zero=False)
text = (f'In {ltdt}, the US labor force has {lfn.iloc[-1]} '+
        f'participants, and the participation rate is {ltv}. One year prior, in {prdt}, '+
        f'labor force participants total {lfn.iloc[-13]}, or {prv} of the age 16 and '+
        'older population. ')
write_txt(text_dir / 'lfpr_summary1.txt', text)
print(text)

# Chart nodes
node = (f'''\\node[above right, align=left] at (axis cs: -0.1,1.13) 
	 	 {{\\footnotesize \\color{{black!80}}Employed}};
		\\node[above right, align=left] at (axis cs: {res.LFPR[1] - res.Unemployed[1]:.1f},1.13) {{Unemp.}};
		\\node[above left, align=right] at (axis cs: {100 - adj:.1f},1.155) 
			{{\\footnotesize \\color{{black!80}}Other \\\\ \\footnotesize \\color{{black!80}} 
              Not in \\\\ \\footnotesize \\color{{black!80}} Labor Force}};
		\\node[above left, align=right] at (axis cs: {res.LFPR[1] + res.WantJob[1]:.1f},1.155) 
            {{\\footnotesize \\color{{black!80}}NILF, \\\\ 
              \\footnotesize \\color{{black!80}}Want \\\\ \\footnotesize \\color{{black!80}} Job}};
		\\draw [thick, black!60!white] (axis cs:0,1.39) -- 
		(axis cs:{res.LFPR[1]:.1f}, 1.39);
		\\node[above, align=center] at (axis cs: {res.LFPR[1] / 2:.1f},1.38) {{\\footnotesize \\color{{black!80}}Participants}};
		\\draw [thick, black!60!white] (axis cs:{res.LFPR[1]:.1f},0.78) -- (axis cs:{100 - adj:.1f}, 0.78);
		\\node[below, align=center] at (axis cs:{(100 - adj) - (((100 - adj) - (res.LFPR[1]))/2):.1f},0.77) 
            {{\\footnotesize \\color{{black!80}}Non-Participants}};
		\\node[below right, align=left] at (axis cs: -0.1,0.835) {{\\footnotesize 
            \\color{{black!80}}Participation Rate: {lt.Employed + lt.Unemployed:.1f} percent}};
		\\node[below right, align=left] at (axis cs: -0.1,-0.165) {{\\footnotesize 
            \\color{{black!80}}Participation Rate: {pr.Employed + pr.Unemployed:.1f} percent}};
		\\node[left, align=right] at (axis cs: {res.LFPR[0] - res.Unemployed[0] - 0.8:.1f},0) {{\\footnotesize \\color{{white}}\\textbf{{{pr.Employed:.1f}}}}};
		\\node[left, align=right] at (axis cs: {res.LFPR[1] - res.Unemployed[1] - 0.8:.1f},1) {{\\footnotesize \\color{{white}}\\textbf{{{lt.Employed:.1f}}}}};
		\\node[align=center] at (axis cs: {res.LFPR[0] - (res.Unemployed[0]/2):.1f},0) {{\\footnotesize \\color{{black!90}}{pr.Unemployed:.1f}}};
		\\node[align=center] at (axis cs: {res.LFPR[1] - (res.Unemployed[1]/2):.1f},1) {{\\footnotesize \\color{{black!90}}{lt.Unemployed:.1f}}};
		\\node[align=center] at (axis cs: {res.LFPR[0] + (res.WantJob[0]/2):.1f},0) {{\\footnotesize \\color{{black!90}}{pr.NILF_WantJob:.1f}}};
		\\node[align=center] at (axis cs: {res.LFPR[1] + (res.WantJob[1]/2):.1f},1) {{\\footnotesize \\color{{black!90}}{lt.NILF_WantJob:.1f}}};
		\\node[right, align=left] at (axis cs: {res.LFPR[0] + res.WantJob[0] + 0.8:.1f},0) {{\\footnotesize \\color{{white}}\\textbf{{{pr.Other_NILF:.1f}}}}};
		\\node[right, align=left] at (axis cs: {res.LFPR[1] + res.WantJob[1] + 0.8:.1f},1) {{\\footnotesize \\color{{white}}\\textbf{{{lt.Other_NILF:.1f}}}}};
		\\node[above right, align=left, fill=white, draw=black!30, inner sep=2.6pt] at (axis cs: -0.3,1.52) 
            {{\\footnotesize {ltdt}}};
		\\node[above right, align=left, fill=white, draw=black!30, inner sep=2.6pt] at (axis cs: -0.3,0.23) 
            {{\\footnotesize {prdt}}};''')
write_txt(text_dir / 'lfpr_summary_node.txt', node)

In December 2025, the US labor force has 171.5 million participants, and the participation rate is 62.4 percent. One year prior, in December 2024, labor force participants total 168.5 million, or 62.5 percent of the age 16 and older population.

In [15]:
# For website
df = (pd.read_csv(data_dir / 'jobs_report_main.csv', 
                  parse_dates=['date'], index_col='date'))
df['Total'].round(1).to_csv('/home/brian/Documents/bdecon.github.io/files/unrate.csv')

In [16]:
df = (pd.read_csv(data_dir / 'jobs_report_main2.csv', 
                  parse_dates=['date'], index_col='date'))
gdp = pd.read_csv(data_dir / 'gdp_monthly.csv', index_col='date', 
                 parse_dates=True)['A191RC']
cpi = pd.read_csv(data_dir / 'cpi_raw.csv', index_col='date',
                 parse_dates=True)['All items']
rgdp = (cpi.loc[df.index[-1]] / cpi) * gdp 
data = (rgdp / df['EMPsa']).dropna()
data.name = 'gdppw'
data = data.to_frame()

df2 = pd.read_csv(data_dir / 'uwe_cps.csv', index_col='date',
                  parse_dates=True)
data['p50'] = (((cpi.loc[df.index[-1]] / cpi) * df2['p50']) * 52) / 1_000
data.dropna().round(1).to_csv('/home/brian/Documents/bdecon.github.io/files/gdppw.csv')

In [17]:
# Read data
df = pd.read_csv(data_dir / 'uwe_cps.csv', index_col='date',
                 parse_dates=True)   
cpi = pd.read_csv(data_dir / 'cpi_raw.csv', index_col='date',
                 parse_dates=True)['All items']
rw = ((cpi.loc[df.index[-1]] / cpi) * df['p10']).dropna()
rw.name = 'value'
rw.round(2).to_csv('/home/brian/Documents/bdecon.github.io/files/p10rw.csv')